// Creativity & Generation vocabulary
// Auto-extracted from semantic-network.jsx

export const creativityNetwork = {
    id: "creativity", label: "Creativity & Generation",
    subtitle: "Poiesis, Desire & the Many Dimensions of Making",
    accent: "#f59e0b", storageKey: "semantic-network-creativity",
    initialNodes: [
      {
        id: "poiesis-cg", term: "Poiesis",
        definition: "The broadest and deepest account of making — bringing-forth that lets things come into presence rather than forcing them to yield calculable results. Poiesis in this vocabulary names the full range of creative acts across all domains: artistic, biological, social, cosmic, contemplative. It is the root from which all other nodes in this vocabulary branch, and the concept that most directly connects making to being. Where production names what is made and for whom, poiesis names the event of making itself — the moment when what did not exist comes into presence through a creative act that could not have been fully anticipated before it happened. This node extends the Poiesis node in the Voice & Vocality vocabulary, which treats poiesis specifically in its linguistic and vocal dimension; here it opens to the full range of creative registers.",
        thinkers: ["Heidegger","Aristotle","Arendt","Plato","Whitehead"],
        tags: ["creativity","ontology","making","philosophy","being"],
        connections: [
          {to:"bhavana",label:"contemplative form of"},
          {to:"production",label:"distinguished from"},
          {to:"craft-cg",label:"embodied form of"},
          {to:"inspiration",label:"receptive mode of"},
          {to:"generativity",label:"future-oriented form of"},
          {to:"cosmopoiesis-cg",label:"cosmic scale of"},
          {to:"autopoiesis-cg",label:"biological form of"},
          {to:"hierophany",label:"poiesis as occasion for"},
          {to:"theoria",label:"contemplative parallel"},
        ],
        nuances: [
          {thinker:"Heidegger",note:"In The Question Concerning Technology, Heidegger distinguishes poiesis from modern technological Herausforderung — challenging-forth, forcing nature to deliver calculable results. Poiesis lets beings come forth into their own presence: the silversmith draws forth what the silver can become rather than imposing a predetermined form. This is making as unconcealment — aletheia enacted through craft."},
          {thinker:"Aristotle",note:"Aristotle distinguishes poiesis from praxis (action directed at its own end) and theoria (contemplation): poiesis produces something that outlasts the making and has its telos outside the act itself — the poem, the building, the institution. The made thing enters the world and becomes available to others, which is why poiesis is inherently social even when practiced alone."},
          {thinker:"Whitehead",note:"For Whitehead, creativity is the ultimate category of existence — not a property of minds but the character of reality as such. Every actual occasion contributes something genuinely new to the universe through its creative advance. Poiesis in the Whiteheadian sense is not a special human capacity but the name for what the universe does at every moment: create."},
          {thinker:"Cross-network",note:"This node extends the Poiesis node in the Voice & Vocality vocabulary, which treats poiesis in its specifically linguistic and vocal dimension. Here the scope is the full range of creative registers: artistic, biological, social, cosmic, and contemplative. The two nodes together constitute poiesis's full breadth."},
        ],
        x:500,y:300,color:"#f59e0b",status:"consolidated",source:"manual",
      },
      {
        id: "bhavana", term: "Bhavana",
        definition: "The Pali term meaning cultivation, development, or bringing-into-being — used in Buddhist practice to name the deliberate cultivation of mental and spiritual qualities through repeated, sustained practice. Bhavana is creation directed inward: not the production of an external object but the development of inner capacities — loving-kindness (metta), concentrated attention (samadhi), insight (vipassana). The meditator creates conditions for transformation rather than transformation itself; bhavana is the art of preparing the ground so that what cannot be forced can arrive. It is the most explicitly contemplative node in this vocabulary and the one that most directly connects creativity to the practices of contemplative governance.",
        thinkers: ["Theravada tradition","Buddhaghosa","Thich Nhat Hanh","Analayo"],
        tags: ["creativity","contemplative","practice","Buddhism","cultivation"],
        connections: [
          {to:"poiesis-cg",label:"contemplative form of"},
          {to:"theoria",label:"parallel contemplative practice"},
          {to:"creatio-continua",label:"continuous cultivation as"},
          {to:"generativity",label:"cultivation oriented toward others"},
          {to:"hierophany",label:"bhavana as preparation for"},
          {to:"conatus",label:"desire that bhavana refines"},
        ],
        nuances: [
          {thinker:"Buddhaghosa",note:"In the Visuddhimagga (Path of Purification, 5th century CE), Buddhaghosa provides the most systematic account of bhavana as a graduated path of cultivation: the meditator develops concentration (samatha) and insight (vipassana) through progressive stages, each creating the conditions for the next. Bhavana is explicitly not about achieving a predetermined state but about the quality of sustained, patient, attentive effort."},
          {thinker:"Cultivation vs. achievement",note:"The key distinction in bhavana is between what can be cultivated and what can only arrive. Attention, compassion, patience, openness — these can be cultivated through practice. Insight, awakening, genuine creativity — these cannot be manufactured but can only be prepared for. Bhavana names the creative act of preparing, which is itself a form of making even when nothing visible is produced."},
          {thinker:"Contemplative governance",note:"Bhavana is directly relevant to contemplative governance as a practice. The cultivation of qualities — equanimity, discernment, compassion, the capacity to hold complexity without premature resolution — is what makes good governance possible. A community that practices bhavana together is developing the collective capacities that governance requires, not as an instrumental exercise but as an end in itself."},
        ],
        x:300,y:160,color:"#c084fc",status:"consolidated",source:"manual",
      },
      {
        id: "production", term: "Production",
        definition: "Marx's foundational category for understanding human creativity in its material and social dimension: the metabolic exchange between human beings and nature through which both are transformed. Production is not mere fabrication — it is the activity through which human beings make themselves by making their world. The worker who shapes raw material into a product expresses their human capacities in the object they make; alienation occurs when this creative dimension is suppressed and production becomes mere labour — the endless reproduction of conditions one did not choose and cannot alter. Production is distinguished from poiesis by its emphasis on the social relations within which making occurs: who owns the means of production, who benefits from what is made, whose creativity is recognised and whose is extracted.",
        thinkers: ["Marx","Arendt","Sennett","Federici"],
        tags: ["creativity","economics","labour","social","material"],
        connections: [
          {to:"poiesis-cg",label:"distinguished from"},
          {to:"craft-cg",label:"production at its best approaches"},
          {to:"labour-work-action",label:"production spans all three"},
          {to:"commons-cg",label:"collective production as"},
          {to:"conatus",label:"desire that production channels"},
          {to:"emergence",label:"production generates emergent effects"},
        ],
        nuances: [
          {thinker:"Marx",note:"For Marx, production is the specifically human form of life-activity: unlike animals who produce instinctively, humans produce consciously, according to a plan that exists in imagination before it exists in reality. This is what makes production a form of poiesis — it involves the human capacity to hold an image of what does not yet exist and bring it into being through purposive activity."},
          {thinker:"Alienation",note:"Alienated production is creation that has lost its poietic dimension: the worker produces but does not recognise themselves in what they make, cannot keep what they make, did not conceive what they make. Alienation is the suppression of creativity within production — the reduction of poiesis to mere labour."},
          {thinker:"Federici",note:"Silvia Federici's work extends the analysis of production to reproductive labour — the caring, nurturing, sustaining work that makes all other production possible but is systematically rendered invisible and uncompensated. Genuine creativity in the full sense must account for reproductive production alongside commodity production."},
        ],
        x:700,y:160,color:"#fb923c",status:"consolidated",source:"manual",
      },
      {
        id: "craft-cg", term: "Craft",
        definition: "The form of creation that most directly unites hand and mind, material and meaning, making and thinking. Richard Sennett's account of the craftsperson — someone who cares about doing something well for its own sake, who develops skill through sustained, attentive practice, who learns from the resistance of materials — is the centre of this node. Craft is poiesis in its most embodied and disciplined form: knowledge that lives in the hands, judgment that cannot be fully articulated, care that exceeds what any specification could require. It is also an ethical form: the craftsperson's commitment to quality is a commitment to the integrity of the made thing and to the person who will use it.",
        thinkers: ["Sennett","Pye","Sloyd tradition","Ruskin","Morris"],
        tags: ["creativity","embodiment","practice","material","ethics"],
        connections: [
          {to:"poiesis-cg",label:"embodied form of"},
          {to:"production",label:"production at its best approaches craft"},
          {to:"labour-work-action",label:"craft as work in Arendt's sense"},
          {to:"vitality",label:"craft as expression of vitality"},
          {to:"mimesis",label:"craft involves mimesis of material"},
        ],
        nuances: [
          {thinker:"Sennett",note:"Richard Sennett's The Craftsman (2008) argues that the separation of hand and head — practical skill from conceptual understanding — is one of the damaging legacies of modernity. The craftsperson develops a dialogue with materials: you do something, the material responds, you adjust. This dialogue is a form of thinking that cannot be replaced by following instructions or applying algorithms."},
          {thinker:"Material resistance",note:"The craftsperson learns from what resists: the wood grain that turns unexpectedly, the clay that cracks, the joint that won't hold. Resistance is not failure but information — it is how materials communicate their nature to the maker. This is the poietic dimension of craft: the made thing is shaped by the conversation between intention and material, not by intention alone."},
          {thinker:"Ruskin and Morris",note:"John Ruskin and William Morris argued that the degradation of craft under industrial production was not merely an aesthetic but a moral catastrophe: it destroyed the worker's capacity for genuine creativity, turning makers into appendages of machines. The Arts and Crafts movement — which directly influenced the Vienna network's Kunstgewerbe — was an attempt to restore craft as a form of human flourishing."},
        ],
        x:300,y:430,color:"#34d399",status:"consolidated",source:"manual",
      },
      {
        id: "inspiration", term: "Inspiration",
        definition: "The older account of artistic and intellectual creation as reception rather than production: the creator as the one through whom something passes rather than the one who originates. Inspiration names the experience — reported across traditions, cultures, and centuries — of ideas, images, forms, and words arriving unbidden, of creation feeling more like discovery than invention, of the made thing exceeding what the maker consciously intended. Plato's Ion describes the poet as magnetically possessed by the Muse; the Hebrew prophets speak as the mouth through which the divine word passes; the scientist reports the solution arriving in a dream. Inspiration does not eliminate skill or effort — it names what happens when skill and effort have prepared a receptivity that allows something to arrive.",
        thinkers: ["Plato","Rilke","Hadamard","Ghiselin","Weil"],
        tags: ["creativity","reception","art","contemplative","mystery"],
        connections: [
          {to:"poiesis-cg",label:"receptive mode of"},
          {to:"hierophany",label:"inspiration as hierophanic event"},
          {to:"bhavana",label:"bhavana prepares for inspiration"},
          {to:"theoria",label:"contemplation as opening to inspiration"},
          {to:"vitality",label:"inspiration as surge of vitality"},
          {to:"eros",label:"eros as the force that inspires"},
        ],
        nuances: [
          {thinker:"Plato",note:"In the Ion, Plato has Socrates describe the poet as a being who creates not through skill (techne) but through divine possession (entheos — having the god within). The poet is like a magnet that receives its charge from the Muse and transmits it to the audience through a chain of inspired reception. This is inspiration in its most radical form: the human creator as pure channel, with no creative agency of their own."},
          {thinker:"Rilke",note:"Rainer Maria Rilke's Letters to a Young Poet and the account of the Duino Elegies arriving — whole and complete — in a state of possession describe inspiration from within the creative act: the experience of the poem arriving rather than being made, of the creator feeling themselves to be the occasion rather than the source. Rilke's account is modern but preserves the essential structure of the classical account."},
          {thinker:"Weil",note:"Simone Weil's concept of attention — the complete evacuation of the self so that what is real can be received — is a contemplative account of inspiration: genuine creativity requires a self-emptying that makes reception possible. Inspiration, on this account, is not the reward for effort but the consequence of a certain quality of attentive openness that effort alone cannot produce."},
        ],
        x:700,y:430,color:"#38bdf8",status:"consolidated",source:"manual",
      },
      {
        id: "generativity", term: "Generativity",
        definition: "Erik Erikson's term for the developmental stage in which the primary concern shifts from personal achievement to contribution: the drive to produce something that will outlast oneself, to care for the next generation, to leave the world richer than one found it. Generativity is creation oriented toward futurity and toward others — making not for oneself but for those who come after, not for recognition but for the continuation of something larger than the maker. It is the ethical dimension of creativity: creation as care, as responsibility, as the acknowledgment that what we make we make for a world we share with others who have not yet arrived.",
        thinkers: ["Erikson","Jonas","Berry","Arendt"],
        tags: ["creativity","ethics","futurity","care","community"],
        connections: [
          {to:"poiesis-cg",label:"future-oriented form of"},
          {to:"commons-cg",label:"generativity as commoning"},
          {to:"labour-work-action",label:"generativity as work and action"},
          {to:"conatus",label:"conatus extended to others"},
          {to:"creatio-continua",label:"generativity as ongoing creation"},
        ],
        nuances: [
          {thinker:"Erikson",note:"In Erikson's developmental schema, generativity — the concern for establishing and guiding the next generation — is the central task of middle adulthood. Its opposite is stagnation: the sense that one is not growing, not contributing, not creating anything that will outlast oneself. Generativity is not only biological; it extends to cultural, intellectual, and institutional creation — anything through which one contributes to a world one will eventually leave."},
          {thinker:"Jonas",note:"Hans Jonas's ethics of responsibility extends generativity into an ontological and political imperative: we have an obligation to ensure that the conditions for genuine human life are preserved for future generations. This is generativity as a moral principle — creation in service of a future whose inhabitants cannot yet speak for themselves."},
          {thinker:"Berry",note:"Wendell Berry's concept of membership — belonging to a place and community across time — is generativity enacted as a form of life: you care for what you have inherited so that those who come after you can inherit something worth having. This is the agricultural and communal form of generativity: the farmer who improves the soil, the community that maintains its commons."},
        ],
        x:700,y:300,color:"#4ade80",status:"consolidated",source:"manual",
      },
      {
        id: "theoria", term: "Theoria",
        definition: "Aristotle's term for the highest human activity: contemplative knowing, the beholding of what is. Theoria is not passive — it is the most intense form of attention, the fullest exercise of the specifically human capacity to know things in their truth. For Aristotle, theoria is creative in the deepest sense: not because it produces an external object but because it brings what is into its fullest presence, makes it available in a way it was not before the contemplating. The scientist, the philosopher, and the contemplative all practice theoria when they attend to what is with complete and disinterested presence. In this vocabulary, theoria names the contemplative dimension of creativity: making through seeing, creating through attending.",
        thinkers: ["Aristotle","Plato","Aquinas","Arendt","Murdoch"],
        tags: ["creativity","contemplative","philosophy","attention","knowledge"],
        connections: [
          {to:"poiesis-cg",label:"contemplative parallel to"},
          {to:"bhavana",label:"parallel contemplative practice"},
          {to:"inspiration",label:"theoria opens to inspiration"},
          {to:"hierophany",label:"theoria as beholding the sacred"},
          {to:"vitality",label:"theoria as concentrated aliveness"},
        ],
        nuances: [
          {thinker:"Aristotle",note:"For Aristotle, theoria is the highest human activity because it is the most self-sufficient, the most continuous, and the most pleasant — it is its own end, requiring nothing outside itself for its completion. The life of theoria is the closest a mortal being can come to the life of the divine. This is not escapism but the fullest expression of the specifically human capacity: the capacity to be fully present to what is."},
          {thinker:"Murdoch",note:"Iris Murdoch's account of moral vision — the capacity to see other people and situations clearly, without the distortions of ego and anxiety — extends theoria into ethics. The good person is one who sees truly, and seeing truly is a creative act: it makes the other more fully present, more fully real, more fully themselves. Theoria as attention that honours what it beholds."},
          {thinker:"Arendt",note:"Arendt distinguishes theoria from her other two fundamental activities (labour and action) and from Aristotle's own tripartite scheme: for Arendt, theoria in the Western tradition has too often been used to justify a withdrawal from the public world, a retreat into the private life of the mind. The creative challenge is to bring contemplative attention into action rather than using it as an escape from action."},
        ],
        x:500,y:160,color:"#a78bfa",status:"consolidated",source:"manual",
      },
      {
        id: "autopoiesis-cg", term: "Autopoiesis",
        definition: "Maturana and Varela's term for the self-producing, self-maintaining organisation characteristic of living systems — a network of processes that produces the components that constitute the network. An autopoietic system creates itself: it is simultaneously the producer and the product of its own organisation. In this vocabulary, autopoiesis names biological creation as the paradigm for understanding all self-sustaining creative processes: the living organism as the model of what it means to be a creative system rather than a creative act. Every living being is an ongoing act of self-creation, and this continuous self-making is the most fundamental form of generativity. This node extends and cross-references the Autopoiesis node in the Worlding vocabulary.",
        thinkers: ["Maturana","Varela","Luhmann","Thompson"],
        tags: ["creativity","biology","process","ontology","life"],
        connections: [
          {to:"poiesis-cg",label:"biological form of"},
          {to:"cosmopoiesis-cg",label:"autopoiesis at cosmic scale"},
          {to:"emergence",label:"autopoiesis produces emergence"},
          {to:"conatus",label:"autopoiesis as organised conatus"},
          {to:"vitality",label:"autopoiesis as the organisation of vitality"},
          {to:"creatio-continua",label:"autopoiesis as continuous creation"},
        ],
        nuances: [
          {thinker:"Maturana & Varela",note:"Autopoiesis was introduced in Autopoiesis and Cognition (1980) to distinguish living from non-living systems by their organisation rather than their material composition. A living system maintains its organisation through the continuous production of its own components — and this self-maintaining circularity is what makes it alive. Life is not a property but a process: a continuous creative act."},
          {thinker:"Luhmann",note:"Niklas Luhmann extended autopoiesis to social systems: communications produce communications in a self-referential network that maintains its own organisation through its own operations. Society is autopoietic in a functional sense — it continuously creates itself through the operations that constitute it. This extension is controversial but opens autopoiesis to the analysis of cultural and institutional creativity."},
          {thinker:"Cross-network",note:"This node extends the Autopoiesis node in the Worlding vocabulary, where autopoiesis grounds the enactivist account of bringing-forth-the-world. Here the focus is on autopoiesis as a model of creativity: what it means to be a self-creating system, and what human creativity looks like when understood in terms of the biological creativity that underlies it."},
        ],
        x:160,y:430,color:"#34d399",status:"consolidated",source:"manual",
      },
      {
        id: "cosmopoiesis-cg", term: "Cosmopoiesis",
        definition: "The world creating itself — the autopoietic, self-organising process by which the cosmos generates, sustains, and transforms itself through its own internal dynamics. At the largest scale of creativity: not human making or even biological making, but the generative creativity of the cosmos as such. Cosmopoiesis resists both the mechanistic image of the universe as a machine running according to external laws and the theological image of creation as the act of an external designer. The cosmos is its own maker; its creativity is immanent and ongoing rather than transcendent and punctual. This node extends and cross-references the Cosmopoiesis node in the Worlding vocabulary.",
        thinkers: ["Whitehead","Stengers","Deleuze","Escobar"],
        tags: ["creativity","cosmology","ontology","process","philosophy"],
        connections: [
          {to:"poiesis-cg",label:"cosmic scale of"},
          {to:"autopoiesis-cg",label:"autopoiesis at cosmic scale"},
          {to:"creatio-continua",label:"theological parallel"},
          {to:"hierophany",label:"cosmopoiesis as the ground of hierophany"},
          {to:"emergence",label:"cosmopoiesis through emergence"},
          {to:"eros",label:"cosmic eros as cosmopoietic force"},
        ],
        nuances: [
          {thinker:"Whitehead",note:"Alfred North Whitehead's process philosophy grounds cosmopoiesis philosophically: reality is a process of creative advance in which each actual occasion contributes something genuinely new to the universe. Creativity is the ultimate category — not a property of minds but the character of the cosmos as such. The universe is not a thing that was created but a process of creating."},
          {thinker:"Stengers",note:"Isabelle Stengers's cosmopolitics draws on cosmopoiesis: her cosmos is not the universe of physics but the undetermined, risky whole of all that is — always more than what any single practice or world-version can capture. Cosmopoiesis is the name for the excess of the cosmos over any account of it."},
          {thinker:"Cross-network",note:"This node extends the Cosmopoiesis node in the Worlding vocabulary, where it grounds the pluriversal account of world-making. Here the focus is on cosmopoiesis as the largest creative context within which all other forms of creativity occur: human making as participation in the cosmos's own self-creating."},
        ],
        x:160,y:280,color:"#e879f9",status:"consolidated",source:"manual",
      },
      {
        id: "eros", term: "Eros",
        definition: "Desire understood as a creative force — not appetite directed at a specific object but the generative energy through which beings reach beyond themselves toward what they do not yet have or are not yet. In Plato's Symposium, Diotima describes Eros as neither mortal nor immortal but a daimon — an intermediary force that moves between human beings and the divine, driving the philosopher toward beauty, truth, and the good. Eros is creative because it is always oriented toward something that exceeds the desiring being: it is the energy of self-transcendence, the force that makes beings larger than themselves. Marcuse's Eros and Civilization argues that Eros in its non-repressive form is the basis of a genuinely creative civilisation.",
        thinkers: ["Plato","Marcuse","Luce Irigaray","Nygren","Murdoch"],
        tags: ["creativity","desire","philosophy","love","aliveness"],
        connections: [
          {to:"conatus",label:"eros as directional conatus"},
          {to:"vitality",label:"eros as the direction of vitality"},
          {to:"inspiration",label:"eros as the force that inspires"},
          {to:"cosmopoiesis-cg",label:"cosmic eros as cosmopoietic force"},
          {to:"poiesis-cg",label:"eros drives poiesis"},
          {to:"hierophany",label:"eros as recognition of the sacred in the other"},
        ],
        nuances: [
          {thinker:"Plato / Diotima",note:"Diotima's account in the Symposium describes Eros as ascending: from the love of a beautiful body, to the love of beautiful bodies in general, to the love of beautiful souls, to the love of beautiful activities and practices, to the love of beauty itself — the Form of Beauty, which is the source of all beautiful things. Each stage is a creative act: the lover who ascends is being made new by what they desire."},
          {thinker:"Marcuse",note:"Herbert Marcuse's Eros and Civilization argues that the repression of Eros — the redirection of erotic energy into alienated labour — is the foundation of authoritarian civilisation. A non-repressive civilisation would allow Eros to flow more freely, producing a culture of genuine creativity, play, and aesthetic sensibility rather than compulsive productivity."},
          {thinker:"Murdoch",note:"Iris Murdoch's account of love as the creative force in both ethics and art connects to eros: the capacity to attend to what is other — a person, a work of art, a moral situation — with genuine love rather than self-projection is the foundation of both good seeing and good making. Eros, on this account, is what makes genuine creativity possible: the pull toward what is truly there rather than what we want to be there."},
        ],
        x:840,y:300,color:"#f472b6",status:"consolidated",source:"manual",
      },
      {
        id: "conatus", term: "Conatus",
        definition: "Spinoza's term for the drive by which each being strives to persist in its own being and increase in its power of acting — the fundamental creative impulse of all existing things. Conatus is not a property that beings have among others; it is what each being fundamentally is: a striving, a reaching, a tendency toward continuation and expression. Desire, on this account, is not a deficit — wanting what you lack — but an excess: the overflow of a being's power of acting into the world. This is Deleuze's reading of Spinoza: desire as production, as the positive energy of existence, not as the mark of incompleteness.",
        thinkers: ["Spinoza","Deleuze","Negri","Damasio"],
        tags: ["creativity","desire","ontology","life","aliveness"],
        connections: [
          {to:"eros",label:"eros as directional conatus"},
          {to:"vitality",label:"conatus as the force of vitality"},
          {to:"autopoiesis-cg",label:"autopoiesis as organised conatus"},
          {to:"poiesis-cg",label:"conatus drives poiesis"},
          {to:"flows-of-desire",label:"conatus as source of desire-flows"},
        ],
        nuances: [
          {thinker:"Spinoza",note:"In the Ethics, Spinoza argues that the conatus of each thing is its actual essence — not something it has but something it is. This means that every being is fundamentally a creative drive: to exist is to strive, and to strive is to act in ways that express and increase one's power of being. Joy, for Spinoza, is the experience of increased power of acting — the felt quality of conatus expressing itself fully."},
          {thinker:"Deleuze",note:"Deleuze reads Spinoza's conatus through his own concept of desire as production: desire is not the desire for something lacking but the positive, productive energy through which assemblages form and transform. Conatus, on this reading, is the name for the creative energy that runs through all of existence — not human desire specifically but the desire that is existence itself."},
          {thinker:"Damasio",note:"Antonio Damasio's neuroscientific work on Spinoza shows that the conatus — the drive to persist and flourish — is not merely a philosophical abstraction but a biological reality: the homeostatic processes by which living organisms maintain and regulate their internal states are the biological embodiment of Spinoza's conatus. The body's self-maintaining creativity is the foundation of all other forms of creativity."},
        ],
        x:840,y:430,color:"#fb923c",status:"consolidated",source:"manual",
      },
      {
        id: "vitality", term: "Vitality",
        definition: "The felt quality of aliveness — not merely being alive but the surplus energy, presence, and receptivity that makes creative engagement possible. Vitality is what distinguishes living from going through the motions: the difference between a performance that is present and one that is technically correct but somehow absent, between a conversation that crackles with genuine exchange and one that merely exchanges information. Bergson's élan vital names the biological dimension — the creative impulse that drives evolution beyond mere adaptation. Rosa's resonance names the social and relational dimension — the felt sense of genuine contact with a world that responds. Vitality is both a precondition for creativity and one of its products: genuine making generates the vitality that makes further making possible.",
        thinkers: ["Bergson","Rosa","Winnicott","Sheets-Johnstone","Laban"],
        tags: ["creativity","aliveness","phenomenology","life","desire"],
        connections: [
          {to:"conatus",label:"vitality as felt conatus"},
          {to:"eros",label:"vitality as the medium of eros"},
          {to:"poiesis-cg",label:"vitality as condition for poiesis"},
          {to:"craft-cg",label:"craft as expression of vitality"},
          {to:"resonance-cg",label:"vitality produced by resonance"},
          {to:"inspiration",label:"inspiration as surge of vitality"},
        ],
        nuances: [
          {thinker:"Bergson",note:"Henri Bergson's élan vital — the vital impetus — names the creative force that drives biological evolution beyond mere mechanical adaptation. Life is not simply the maintenance of existing forms but the continuous creation of new ones: the élan vital is the name for this creative excess that produces novelty. Bergson sees duration — lived time, qualitative time — as the medium in which vitality expresses itself."},
          {thinker:"Rosa",note:"Hartmut Rosa's account of resonance connects vitality to relation: we feel most alive when we are genuinely in contact with something that responds to us and that we genuinely respond to. Vitality is not a private property of the self but an emergent quality of genuine relation — which is why isolation, bureaucracy, and a-resonant environments suppress it. The creative act restores vitality by establishing genuine contact."},
          {thinker:"Winnicott",note:"D.W. Winnicott's concept of the capacity for creative living — what he calls aliveness — is distinguished from mere compliance or adaptation: the truly alive person brings something of themselves to each encounter rather than simply fitting into what is expected. This aliveness is what creativity both requires and produces: you cannot make genuinely unless you are genuinely alive, and the act of genuine making deepens aliveness."},
        ],
        x:840,y:160,color:"#4ade80",status:"consolidated",source:"manual",
      },
      {
        id: "creatio-continua", term: "Creatio Continua",
        definition: "The theological concept of continuous creation: not a single originating act at the beginning of time but an ongoing creative sustaining of existence at every moment. God, on this account, is not primarily first cause but the continuous ground of being — the creative source from which existence is perpetually renewed. Without this continuous creative act, things would not merely stop changing; they would cease to be. Creatio continua shifts the emphasis from creation as a past event to creation as the present condition of all existence: the world is always being made, never simply given. This connects directly to Whitehead's cosmology, to autopoiesis, and to the contemplative sense that reality is a continuous creative event rather than a settled background.",
        thinkers: ["Aquinas","Meister Eckhart","Moltmann","Whitehead","Teilhard de Chardin"],
        tags: ["creativity","theology","ontology","contemplative","time"],
        connections: [
          {to:"poiesis-cg",label:"divine poiesis as continuous"},
          {to:"autopoiesis-cg",label:"biological parallel"},
          {to:"cosmopoiesis-cg",label:"secular parallel"},
          {to:"bhavana",label:"continuous cultivation parallel"},
          {to:"generativity",label:"continuous creation as generativity"},
          {to:"hierophany",label:"creatio continua as condition for hierophany"},
        ],
        nuances: [
          {thinker:"Aquinas",note:"For Aquinas, creatio continua is not a supplement to the original creation but its continuation: God does not create once and then sustain what was made, but the act of creation is identical with the act of conservation — to sustain something in being is to create it continuously. This makes creation a present, ongoing reality rather than a past event."},
          {thinker:"Meister Eckhart",note:"Eckhart radicalises creatio continua into a mystical claim: God is always giving birth to the Word in the soul, and the soul's deepest activity is to receive this continuous birth. Creation is not something that happened to the world but something that is happening in the soul at every moment — which is why contemplation is not a withdrawal from creation but its most concentrated form."},
          {thinker:"Teilhard de Chardin",note:"Pierre Teilhard de Chardin's evolutionary theology extends creatio continua forward: creation is not yet finished — the universe is moving toward a final fulfilment (the Omega Point) through the ongoing creative process of complexification. Human creativity is participation in this ongoing divine creativity — the universe becoming conscious of and contributing to its own creation."},
        ],
        x:300,y:300,color:"#818cf8",status:"consolidated",source:"manual",
      },
      {
        id: "hierophany", term: "Hierophany",
        definition: "Mircea Eliade's term for the irruption of the sacred into the profane — the moment when an ordinary object, place, person, or act becomes the site of an encounter with something that exceeds it. A stone, a tree, a ritual gesture, a work of art: any of these can become hierophanic — not because the sacred was imported from outside but because the ordinary disclosed a depth that was always there, waiting to be encountered by someone capable of receiving it. Hierophany is the paradox at the heart of creation: the made thing sometimes becomes more than what was made, the creative act sometimes opens onto what cannot be made. Heidegger's aletheia — truth as unconcealment, the world showing itself rather than being forced to yield — is the secular philosophical parallel: both name the event in which something arrives that was not produced.",
        thinkers: ["Eliade","Otto","Heidegger","Corbin","Marion"],
        tags: ["creativity","sacred","ontology","phenomenology","religion"],
        connections: [
          {to:"poiesis-cg",label:"poiesis as occasion for hierophany"},
          {to:"inspiration",label:"inspiration as hierophanic experience"},
          {to:"theoria",label:"theoria as beholding hierophany"},
          {to:"creatio-continua",label:"hierophany as encounter with continuous creation"},
          {to:"bhavana",label:"bhavana as preparation for hierophany"},
          {to:"cosmopoiesis-cg",label:"cosmopoiesis as ground of hierophany"},
        ],
        nuances: [
          {thinker:"Eliade",note:"For Eliade, hierophany is the fundamental structure of religious experience: the sacred always manifests through the profane without being identified with it. The hierophanic object is simultaneously what it ordinarily is and the site of a disclosure that exceeds its ordinary being. Sacred stones, sacred trees, sacred persons — all are hierophanies: ordinary things that have become the occasion for an encounter with what Eliade calls the wholly other."},
          {thinker:"Otto",note:"Rudolf Otto's The Idea of the Holy (1917) describes the experience of the numinous — the mysterium tremendum et fascinans — that hierophany occasions: the simultaneous experience of overwhelming otherness (tremendum) and irresistible attraction (fascinans). The creative act at its most intense has this quality: the made thing that arrives as a gift, the insight that arrives as a visitation, the encounter that exceeds what was intended."},
          {thinker:"Heidegger / Aletheia",note:"Heidegger's concept of aletheia — truth as unconcealment, from the Greek a-letheia, the undoing of hiddenness — is the secular philosophical parallel to hierophany. Truth, for Heidegger, is not the correspondence of a statement to a fact but the event of something showing itself — the world opening rather than being forced open. Both hierophany and aletheia name the creative event in which something arrives that cannot be produced but only received: the disclosure that is neither manufactured nor merely found."},
          {thinker:"In this vocabulary",note:"Hierophany occupies the place that was initially proposed for 'constraint and creation' — but it addresses the paradox from the other side. Where constraint and creation says that limitation enables making, hierophany says that making sometimes opens onto what cannot be made. Together they frame the paradox of creativity: the creative act is both enabled by limits and exceeded by what arrives through it."},
        ],
        x:500,y:450,color:"#f59e0b",status:"consolidated",source:"manual",
      },
      {
        id: "emergence", term: "Emergence",
        definition: "The phenomenon in which properties, patterns, or forms arise in a system that could not have been predicted from the properties of the system's components taken individually. Emergence is creation without a creator: the new form is produced by the interactions of parts without any single part or external agent intending or designing it. The flock's murmuration, the ant colony's architecture, the market's price, the community's culture — all are emergent. In the context of creativity, emergence names what happens at the intersection of many creative acts: the surplus of collective making that no individual making intended. This is why genuine creativity is often more than the sum of its inputs.",
        thinkers: ["Holland","Kauffman","Deacon","Stengers","Johnson"],
        tags: ["creativity","systems","process","complexity","ontology"],
        connections: [
          {to:"autopoiesis-cg",label:"autopoiesis produces emergence"},
          {to:"cosmopoiesis-cg",label:"emergence at cosmic scale"},
          {to:"commons-cg",label:"commoning produces emergent commons"},
          {to:"poiesis-cg",label:"emergence as non-intentional poiesis"},
          {to:"vitality",label:"emergence generates vitality"},
          {to:"hierophany",label:"emergence as secular hierophany"},
        ],
        nuances: [
          {thinker:"Kauffman",note:"Stuart Kauffman's work on self-organisation in complex systems shows that emergence is not merely an interesting phenomenon but a fundamental feature of the universe: the biosphere itself is an emergent phenomenon, and the capacity for emergence — for genuinely new forms to arise from the interaction of simpler elements — is what makes evolution, creativity, and life itself possible."},
          {thinker:"Deacon",note:"Terrence Deacon's Incomplete Nature argues that emergence involves not just the presence of new properties but the causal efficacy of absences — constraints, boundaries, and the not-yet-realised potential that shapes what becomes actual. Emergence is creative precisely because it is not fully determined by what precedes it: the new form carries something genuinely new into the world."},
          {thinker:"Community creativity",note:"The most important form of emergence for this vocabulary is social and cultural: the creativity that arises when a community of practice develops its own shared language, its own modes of inquiry, its own forms of life — none of which any individual member intended or designed, but all of which are genuinely produced by the collective interaction. A vocabulary is an emergent phenomenon of this kind."},
        ],
        x:160,y:160,color:"#38bdf8",status:"consolidated",source:"manual",
      },
      {
        id: "commons-cg", term: "Commons / Commoning",
        definition: "Creation as collective, shared, and non-proprietary — the making of goods, knowledge, practices, and forms of life that belong to no one and therefore to everyone. Commoning, from Bollier and Helfrich, names the active process of creating and sustaining a commons: not a thing but an ongoing practice of negotiation, care, and collective stewardship. The commons is always being made; it is never simply given or preserved. In the context of this vocabulary, commoning is the specifically social form of generativity: the community that tends its commons is continuously creating the conditions for collective flourishing, and the commons that results is the emergent product of that continuous creative care.",
        thinkers: ["Bollier","Helfrich","Ostrom","Federici","Linebaugh"],
        tags: ["creativity","commons","community","social","ethics"],
        connections: [
          {to:"generativity",label:"commoning as collective generativity"},
          {to:"emergence",label:"commons as emergent creation"},
          {to:"craft-cg",label:"commoning as collective craft"},
          {to:"autopoiesis-cg",label:"commons as social autopoiesis"},
          {to:"production",label:"collective production as commoning"},
        ],
        nuances: [
          {thinker:"Bollier & Helfrich",note:"In Free, Fair and Alive (2019), Bollier and Helfrich argue that a commons is not primarily a resource but a social system: the commoners, their practices, and their shared resource together constitute the commons. Commoning — the verb — emphasises the ongoing creative act of making and remaking the commons through practice. The commons is never finished; it is always being created."},
          {thinker:"Ostrom",note:"Elinor Ostrom's empirical work showed that communities can successfully manage shared resources without privatisation or state control — through locally evolved rules, monitoring, and sanctions. Her eight design principles for sustainable commons governance are a description of the creative practices through which communities maintain the conditions for collective flourishing over time."},
          {thinker:"Linebaugh",note:"Peter Linebaugh's The Magna Carta Manifesto recovers the history of commoning as a creative practice: the common people of medieval England did not merely use the forest commons but actively made it through their practices of gathering, grazing, and stewardship. The enclosure of the commons was not merely the appropriation of land but the destruction of a creative form of life."},
        ],
        x:160,y:540,color:"#34d399",status:"consolidated",source:"manual",
      },
      {
        id: "labour-work-action", term: "Labour, Work & Action",
        definition: "Hannah Arendt's tripartite distinction in The Human Condition, here read through the lens of creativity. Labour is the biological process of sustaining life — cyclical, endless, consuming what it produces, leaving no permanent trace. Work is the fabrication of a durable world — objects, institutions, stories, vocabularies that outlast the lives of their makers and create a common world for others to inhabit. Action is the capacity to begin something genuinely new in the public realm — to initiate, to appear, to be seen, to take a risk on what has no guarantee. The three are different modes of human creativity: labour creates conditions; work creates objects; action creates events. A genuinely creative life involves all three, but in modern economies labour tends to expand until it crowds out work and action.",
        thinkers: ["Arendt","Marx","Sennett","Castoriadis"],
        tags: ["creativity","labour","politics","ontology","philosophy"],
        connections: [
          {to:"poiesis-cg",label:"work as the poietic mode"},
          {to:"production",label:"production spans all three"},
          {to:"craft-cg",label:"craft as work in Arendt's sense"},
          {to:"commons-cg",label:"action creates commons"},
          {to:"generativity",label:"work and action as generative"},
        ],
        nuances: [
          {thinker:"Arendt",note:"Arendt's distinctions resist collapse: labour is not simply repetitive work, and action is not simply important work. Each has its own logic, its own temporality, and its own relation to the world. Labour is cyclical and necessary; work is linear and fabricative; action is plural and unpredictable. The tragedy of modernity, for Arendt, is the reduction of all human activity to the metabolism of labour — the endless production and consumption that leaves nothing durable."},
          {thinker:"Action as creation",note:"Arendt's account of action is the most radically creative: action is the capacity to begin — to introduce something genuinely new into a world that was there before the actor and will continue after them. This is creativity in its most existential sense: the courage to initiate, to appear, to take responsibility for what one has started without knowing how it will end."},
          {thinker:"Cross-network",note:"This node extends the Arendt Triad node in the Livelihoods vocabulary, where it frames the question of what a livelihood is. Here the emphasis is on the three modes as modes of creativity: how each one makes something, what each one makes, and what kind of world each one requires and produces."},
        ],
        x:500,y:550,color:"#818cf8",status:"consolidated",source:"manual",
      },
      {
        id: "mimesis", term: "Mimesis",
        definition: "Aristotle's account of artistic creation as imitation — but understood in its full philosophical complexity rather than as mere copying. Mimesis is creative precisely because it is not mere reproduction: the artist who imitates nature or human action reveals something about what is imitated that direct experience does not. Tragedy imitates action not to record it but to disclose its universal form — the pattern that makes particular actions recognisable as human. The craftsperson who imitates the grain of wood is not copying but following, learning from, entering into dialogue with the material. Mimesis, on this account, is creation through attentive imitation: learning the world by following it closely enough to reveal what it is.",
        thinkers: ["Aristotle","Auerbach","Girard","Ricoeur","Benjamin"],
        tags: ["creativity","art","imitation","philosophy","narrative"],
        connections: [
          {to:"poiesis-cg",label:"mimesis as poietic mode"},
          {to:"craft-cg",label:"craft involves mimesis of material"},
          {to:"theoria",label:"mimesis requires theoria"},
          {to:"inspiration",label:"mimesis as receptive creation"},
          {to:"labour-work-action",label:"mimesis as work"},
        ],
        nuances: [
          {thinker:"Aristotle",note:"In the Poetics, Aristotle argues that mimesis is natural to human beings from childhood — it is how we learn — and that the pleasure of artistic mimesis is the pleasure of recognition: seeing that this is that, that the imitation discloses something true about what is imitated. Tragedy is not a copy of suffering but a creative disclosure of its universal form."},
          {thinker:"Ricoeur",note:"Paul Ricoeur's threefold mimesis in Time and Narrative distinguishes pre-figuration (the understanding of action that makes narrative possible), configuration (the creative act of emplotment — turning events into a story), and re-figuration (the transformation of the reader by the story received). Mimesis on this account is not imitation of a finished reality but the creative mediation through which reality is constituted for human experience."},
          {thinker:"Benjamin",note:"Walter Benjamin's account of the mimetic faculty — the human capacity to produce and perceive similarities — treats mimesis as a fundamental mode of relating to the world: not copying but corresponding, entering into a relationship of likeness with what is other. The child who plays at being a windmill, the writer who follows the rhythm of what they describe — both are exercising the mimetic faculty as a creative act."},
        ],
        x:840,y:540,color:"#c084fc",status:"consolidated",source:"manual",
      },
    ],
  };
