// Distributed Situational Awareness vocabulary
// Auto-extracted from semantic-network.jsx

export const dsaNetwork = {
    id: "dsa", label: "Distributed Situational Awareness",
    subtitle: "Cobana — Collective Sensing, Place & the More-Than-Human Field",
    accent: "#34d399", storageKey: "semantic-network-dsa",
    initialNodes: [
      {
        id: "dsa-core", term: "Distributed Situational Awareness",
        definition: "Awareness understood not as a property of any individual mind but as something that emerges from and circulates through a whole system — the ongoing, dynamic field of knowing that arises from the interactions between people, place, tools, and the more-than-human world. No single node holds the full picture; each holds a partial view, and the system's awareness is constituted by how these partial views are distributed, shared, translated, and held in tension. At Cobana, DSA names the aspiration that the community itself — not any one coordinator or visitor — becomes the sensing and sensemaking organ of its own life and work.",
        thinkers: ["Endsley","Hutchins","Haraway","Ingold"],
        tags: ["DSA","awareness","community","systems","place"],
        connections: [
          {to:"situation-awareness",label:"extends and distributes"},
          {to:"distributed-cognition",label:"grounded in"},
          {to:"perception-dsa",label:"first movement of"},
          {to:"comprehension",label:"second movement of"},
          {to:"projection",label:"third movement of"},
          {to:"partial-view",label:"constituted by"},
          {to:"relational-trust",label:"sustained by"},
          {to:"more-than-human",label:"extended into"},
          {to:"vocality-dsa",label:"requires genuine"},
        ],
        nuances: [
          {thinker:"Hutchins",note:"Edwin Hutchins's Cognition in the Wild (1995) showed that the navigation crew of a ship does not navigate by pooling individually computed solutions — the computation is achieved through the coordinated activity of people and instruments together. DSA draws on this insight: the community's awareness is not the sum of individual awarenesses but an emergent property of their coordinated interaction."},
          {thinker:"Haraway",note:"Donna Haraway's situated knowledges and tentacular thinking provide the epistemological framework: no view from nowhere, partial perspectives linked rather than unified, accountability to the specific positions from which knowledge is made. DSA is Haraway's epistemology made into a community practice."},
          {thinker:"Cobana context",note:"At Cobana in the Carpathians, DSA is not an abstract methodology but a specific aspiration: to cultivate the conditions under which the community itself — including its more-than-human members — becomes the primary sensing and sensemaking organ of its own life, work, and place."},
        ],
        x:500,y:300,color:"#34d399",status:"consolidated",source:"paper",
      },
      {
        id: "situation-awareness", term: "Situation Awareness",
        definition: "The foundational concept from which DSA develops — originally formulated by Mica Endsley as the perception of elements in an environment, the comprehension of their meaning, and the projection of their near-future status. Endsley's model emerged from aviation and human factors research: the concern was how a pilot could maintain an adequate real-time picture of a fast-moving, high-stakes situation. The model is hierarchical and individual — one person, three cognitive levels — and it is precisely this individuality that DSA later challenges. But the intuition at its core remains: effective action requires not just information but a live, integrated sense of what is happening and what is likely to happen next.",
        thinkers: ["Endsley","Klein","Woods"],
        tags: ["DSA","awareness","cognition","epistemology","systems"],
        connections: [
          {to:"dsa-core",label:"distributed into"},
          {to:"perception-dsa",label:"first level"},
          {to:"comprehension",label:"second level"},
          {to:"projection",label:"third level"},
          {to:"distributed-cognition",label:"individualised version expanded by"},
        ],
        nuances: [
          {thinker:"Endsley",note:"Endsley's three-level model — perception, comprehension, projection — was developed for high-stakes individual decision-making in aviation, air traffic control, and military contexts. Its value is its precision about the cognitive structure of awareness; its limitation is that it treats awareness as a property of an individual mind operating in a determinate environment."},
          {thinker:"Limitations",note:"The move from Situation Awareness to Distributed Situational Awareness is not merely a scaling up — it involves a fundamental reconception. In DSA, the 'situation' is not a fixed environment perceived by a subject but a relational field that is partially constituted by the act of perceiving it. The partial view is not a limitation on full awareness but the basic condition of all knowing."},
        ],
        x:280,y:160,color:"#38bdf8",status:"consolidated",source:"paper",
      },
      {
        id: "distributed-cognition", term: "Distributed Cognition",
        definition: "The claim, developed most fully by Edwin Hutchins, that cognitive processes are not confined to individual minds but are spread across people, artefacts, and the physical environment in which they are embedded. A navigation crew does not navigate by pooling individually computed solutions — the computation is achieved through the coordinated activity of people and instruments together. At Cobana, distributed cognition names the way that the community's intelligence is held not only by its members but by its spaces, rhythms, practices, and accumulated objects.",
        thinkers: ["Hutchins","Clark","Kirsh","Norman"],
        tags: ["DSA","cognition","systems","embodiment","community"],
        connections: [
          {to:"dsa-core",label:"theoretical ground of"},
          {to:"situation-awareness",label:"distributes"},
          {to:"tacit-knowledge",label:"includes"},
          {to:"place-knowledge",label:"place as cognitive node"},
          {to:"information-flow",label:"sustained by"},
          {to:"more-than-human",label:"extended beyond human"},
        ],
        nuances: [
          {thinker:"Hutchins",note:"Hutchins's key insight is that the unit of analysis for cognition should be the functional system rather than the individual mind. The ship's bridge is a cognitive system: it includes the navigators, the charts, the instruments, the spatial layout, and the accumulated practices encoded in procedures and conventions. Intelligence is in the system, not merely in the heads of its members."},
          {thinker:"Clark",note:"Andy Clark's extended mind thesis argues that cognitive processes can extend beyond the skin: a notebook, a smartphone, or a community's shared practices can be constitutive parts of a cognitive system rather than merely aids to an individual mind. At Cobana, the landscape itself is an extended cognitive system — a repository of place knowledge that participates in the community's collective awareness."},
        ],
        x:160,y:280,color:"#818cf8",status:"consolidated",source:"paper",
      },
      {
        id: "perception-dsa", term: "Perception",
        definition: "The first movement of situational awareness: the noticing of what is present, what has changed, what is absent that was expected, what is there that was not anticipated. Distributed across a community, perception becomes a collective practice of noticing — cultivated through slowing down, attending, naming what is here. At Cobana, perception includes not only what members and guests notice in human terms, but what the place itself makes legible: weather, animal movement, plant phenology, the quality of light, the texture of silence. Perception is not passive reception but an active, trained, and distributed practice of attention.",
        thinkers: ["Gibson","Merleau-Ponty","Ingold","Weil"],
        tags: ["DSA","perception","attention","place","embodiment"],
        connections: [
          {to:"dsa-core",label:"first movement of"},
          {to:"situation-awareness",label:"first level of"},
          {to:"comprehension",label:"leads into"},
          {to:"more-than-human",label:"perceiving more-than-human field"},
          {to:"threshold-awareness",label:"thresholds heighten"},
          {to:"tacit-knowledge",label:"perception carries tacit knowing"},
          {to:"seasonal-rhythms",label:"attuned to"},
        ],
        nuances: [
          {thinker:"Gibson",note:"James Gibson's ecological perception — the idea that organisms perceive affordances (possibilities for action) rather than raw sensory data — frames perception as inherently relational: you perceive what the environment offers for action, not a neutral representation of it. At Cobana, distributed perception means cultivating sensitivity to the affordances that the place and community offer."},
          {thinker:"Weil",note:"Simone Weil's concept of attention — the complete, self-evacuating presence to what is actually there — is the contemplative dimension of perception in the DSA sense. Genuine perception requires the suppression of the projecting self: attending to what is rather than what is expected or desired. This is a practice and a discipline, not a natural capacity."},
          {thinker:"Ingold",note:"Tim Ingold's account of perception as skilled attunement — developed through sustained practice in a particular environment — grounds DSA perception in the body and in place. To perceive well is to have learned to attend to what matters in this specific environment, which is why place knowledge and perception are inseparable."},
        ],
        x:300,y:430,color:"#4ade80",status:"consolidated",source:"paper",
      },
      {
        id: "comprehension", term: "Comprehension",
        definition: "The second movement of situational awareness: making sense of what has been perceived — integrating observations into understanding, identifying patterns, recognising what a situation means rather than merely what it contains. In distributed form, comprehension is collective sensemaking: the process by which a community moves from scattered observations to shared understanding. At Cobana, comprehension is where conversation, dialogue, and structured reflection become DSA practices — where what different people have noticed is brought into relation and interpreted together. Comprehension is never complete; it is always provisional, always subject to revision as new perceptions arrive.",
        thinkers: ["Weick","Hutchins","Bohm","Isaacs"],
        tags: ["DSA","sensemaking","dialogue","community","knowledge"],
        connections: [
          {to:"dsa-core",label:"second movement of"},
          {to:"situation-awareness",label:"second level of"},
          {to:"perception-dsa",label:"follows from"},
          {to:"projection",label:"enables"},
          {to:"relational-trust",label:"requires for honest sharing"},
          {to:"partial-view",label:"integrates"},
          {to:"information-flow",label:"sustained by"},
          {to:"blending-voices",label:"practised through"},
        ],
        nuances: [
          {thinker:"Weick",note:"Karl Weick's sensemaking framework — the retrospective process by which people make sense of equivocal situations — is the organisational theory closest to DSA comprehension. For Weick, sensemaking is ongoing, social, and never complete: the sense made is always provisional and subject to disruption by new events. Comprehension in a community is always collective sensemaking in this sense."},
          {thinker:"Bohm",note:"David Bohm's concept of dialogue — a quality of conversation in which meaning flows through rather than being exchanged between participants — names the ideal form of distributed comprehension. In genuine dialogue, the group thinks together rather than competing to have their individual views prevail. This is comprehension as a collective cognitive act."},
        ],
        x:500,y:430,color:"#a78bfa",status:"consolidated",source:"paper",
      },
      {
        id: "projection", term: "Projection",
        definition: "The third movement of situational awareness: anticipating what is likely to happen next, extrapolating from current understanding to near-future states. Distributed, projection becomes collective anticipation — the community's capacity to orient itself toward its emerging future, to notice early signals of change, to imagine alternative trajectories. At Cobana, projection includes both near-term operational anticipation (what do guests need next? what does the season require?) and longer-term orientation (what is this place becoming? what is wanted from us?). Projection held too confidently closes down awareness; held lightly, it keeps the community oriented without premature foreclosure.",
        thinkers: ["Endsley","Scharmer","Ingold","Weick"],
        tags: ["DSA","anticipation","futures","community","orientation"],
        connections: [
          {to:"dsa-core",label:"third movement of"},
          {to:"situation-awareness",label:"third level of"},
          {to:"comprehension",label:"follows from"},
          {to:"seasonal-rhythms",label:"structured by"},
          {to:"partial-view",label:"projection as partial anticipation"},
          {to:"more-than-human",label:"projection includes more-than-human signals"},
        ],
        nuances: [
          {thinker:"Scharmer",note:"Otto Scharmer's Theory U distinguishes downloading (projecting from past patterns), seeing (perceiving the present freshly), and presencing (sensing the emerging future). DSA projection at its best is not downloading but presencing — attending to what is trying to emerge rather than extrapolating from what has been."},
          {thinker:"Seasonal projection",note:"At Cobana, the seasonal calendar provides a non-human structure for projection: the community orients not only to its own plans but to what the season is calling for — what the land needs, what the ecological cycle is asking, what the traditional calendar encodes about this time of year. This is projection anchored in more-than-human temporality."},
        ],
        x:700,y:430,color:"#fb923c",status:"consolidated",source:"paper",
      },
      {
        id: "partial-view", term: "Partial View",
        definition: "The foundational epistemological claim of distributed systems: no node in a network sees the whole. Every participant in a DSA system holds a partial view — shaped by their position, their history, their skills, their relationship to the place. Partial views are not deficiencies to be corrected by centralising information; they are the irreducible condition of distributed knowing. The system's awareness arises from the interaction of partial views, not from any single comprehensive perspective. At Cobana, the partial views of long-term members, short-term residents, guests, local partners, and the place itself are all necessary contributions to the full field — none is privileged, none is sufficient.",
        thinkers: ["Haraway","Hutchins","Tsing","Star"],
        tags: ["DSA","epistemology","plurality","knowledge","community"],
        connections: [
          {to:"dsa-core",label:"DSA constituted by"},
          {to:"comprehension",label:"comprehension integrates"},
          {to:"relational-trust",label:"sharing requires trust"},
          {to:"vocality-dsa",label:"each voice carries a partial view"},
          {to:"situated-knowledge-dsa",label:"partial view as situated knowledge"},
          {to:"threshold-awareness",label:"arrival offers fresh partial view"},
        ],
        nuances: [
          {thinker:"Haraway",note:"Haraway's situated knowledges — the claim that all knowledge is produced from a specific position and that partial perspectives can be linked but not transcended — is the philosophical grounding of partial view. The view from nowhere is not possible and not desirable; what is possible is the linking of specific, accountable, partial perspectives into something richer than any one of them."},
          {thinker:"Star",note:"Susan Leigh Star's boundary objects — artefacts, concepts, or practices that are plastic enough to adapt to different communities of practice while robust enough to maintain a common identity — show how partial views can be coordinated without being unified. DSA systems require boundary objects through which partial views can meet and translate across difference."},
        ],
        x:700,y:280,color:"#facc15",status:"consolidated",source:"paper",
      },
      {
        id: "relational-trust", term: "Relational Trust",
        definition: "The interpersonal and communal fabric that makes the sharing of partial views possible. Without relational trust, DSA collapses into information hoarding, performative awareness, and the silencing of inconvenient observations. With it, people are able to say what they actually see, to not-know in public, to offer partial views without needing them to be complete, to hear others' views without defensiveness. Relational trust at Cobana is not simply a product of good interpersonal relations — it is itself a practice, cultivated through the rhythms of shared life, the quality of arrival and departure, the consistency of care, and the integrity of follow-through. Trust is the medium through which distributed awareness becomes shared awareness.",
        thinkers: ["Ostrom","Sennett","Putnam","Weil"],
        tags: ["DSA","trust","community","practice","relation"],
        connections: [
          {to:"dsa-core",label:"sustains"},
          {to:"partial-view",label:"makes sharing possible"},
          {to:"comprehension",label:"enables honest"},
          {to:"hosting-structure",label:"cultivated through"},
          {to:"vocality-dsa",label:"trust enables genuine voice"},
          {to:"information-flow",label:"trust opens flow"},
        ],
        nuances: [
          {thinker:"Ostrom",note:"Elinor Ostrom's empirical work on commons governance shows that trust is not a pre-condition for collective action but an achievement of it: communities build trust through repeated interactions, demonstrated reliability, and the experience of shared stewardship. Trust is produced by the practices that require it, not merely imported into them."},
          {thinker:"Sennett",note:"Richard Sennett's account of cooperation — in Together: The Rituals, Pleasures and Politics of Cooperation — shows that cooperation across difference requires the skills of listening, of empathetic imagination, and of tolerating incompleteness. These are craft skills of relationship, developed through practice. Relational trust in DSA terms is the ongoing practice of these skills."},
        ],
        x:840,y:160,color:"#f472b6",status:"consolidated",source:"paper",
      },
      {
        id: "tacit-knowledge", term: "Tacit Knowledge",
        definition: "Knowledge that is carried in the body, in practice, in felt sense — that cannot be fully made explicit without loss. Polanyi's formulation — 'we know more than we can tell' — names the excess of knowing that DSA must somehow include. At Cobana, tacit knowledge includes the long-term member's felt sense of when the community needs rest rather than stimulation; the cook's knowledge of what the season's harvest calls for; the gardener's reading of soil and weather; the host's attunement to a guest's unspoken need. DSA systems that only circulate explicit information miss most of what the community actually knows.",
        thinkers: ["Polanyi","Collins","Sennett","Dreyfus"],
        tags: ["DSA","knowledge","embodiment","practice","craft"],
        connections: [
          {to:"distributed-cognition",label:"distributed cognition includes"},
          {to:"perception-dsa",label:"perception carries tacit knowing"},
          {to:"place-knowledge",label:"place knowledge is largely tacit"},
          {to:"information-flow",label:"tacit knowledge resists explicit flow"},
          {to:"hosting-structure",label:"hosting cultivates tacit attunement"},
        ],
        nuances: [
          {thinker:"Polanyi",note:"Michael Polanyi introduced the concept in Personal Knowledge (1958) and The Tacit Dimension (1966): all knowledge has a tacit component, and the explicit is always subsidiary to a tacit background that gives it meaning. The surgeon knows things the anatomy textbook cannot contain; the musician knows things the score cannot capture. DSA must find ways to honour and circulate tacit knowing, not only explicit information."},
          {thinker:"Collins",note:"Harry Collins distinguishes different kinds of tacit knowledge: relational (dependent on social relationships), somatic (embodied in the body), and collective (distributed across a community of practice). At Cobana, all three are at work: the community's awareness is partly constituted by tacit knowledge that no individual holds and that cannot be made fully explicit."},
        ],
        x:160,y:430,color:"#fb923c",status:"consolidated",source:"paper",
      },
      {
        id: "place-knowledge", term: "Place Knowledge",
        definition: "The knowledge that is specific to, and only fully accessible from within, a particular place — accumulated through sustained dwelling, perceptual attunement, and intimate engagement with the living systems of a location. At Cobana, place knowledge includes knowledge of the Carpathian ecosystem, of seasonal rhythms specific to this altitude and valley, of the cultural and historical layers of Transylvania, of the way the community works with this particular land. Place knowledge is a primary node in Cobana's DSA: it is what distinguishes the awareness of those who have dwelt here from those passing through.",
        thinkers: ["Ingold","Kimmerer","Berry","Snyder"],
        tags: ["DSA","place","ecology","knowledge","dwelling"],
        connections: [
          {to:"distributed-cognition",label:"place as cognitive node"},
          {to:"tacit-knowledge",label:"largely tacit"},
          {to:"more-than-human",label:"includes more-than-human knowledge"},
          {to:"seasonal-rhythms",label:"organised by"},
          {to:"bioregionalism",label:"bioregional framing of"},
          {to:"perception-dsa",label:"deepens perception"},
          {to:"threshold-awareness",label:"long-term members hold"},
        ],
        nuances: [
          {thinker:"Kimmerer",note:"Robin Wall Kimmerer's Braiding Sweetgrass shows that genuine place knowledge requires learning the language of a place — its species, its patterns, its seasonal logic — in a way that involves reciprocity and relationship, not merely observation and recording. Place knowledge at Cobana means entering into relationship with the Carpathian ecosystem, not simply studying it."},
          {thinker:"Berry",note:"Wendell Berry's concept of membership — belonging to a place over time, accumulating obligation and knowledge together — is the ethical dimension of place knowledge. You know a place more truly by belonging to it, by being responsible to it, than by observing it from a distance. This is why long-term dwelling produces a qualitatively different kind of knowledge than even attentive visiting."},
        ],
        x:160,y:540,color:"#4ade80",status:"consolidated",source:"paper",
      },
      {
        id: "information-flow", term: "Information Flow",
        definition: "The channels, rhythms, and media through which awareness circulates within and beyond the DSA system. Information flow is not simply the transmission of data — it includes the form of sharing (conversation, story, gesture, written record), the timing (daily check-ins, seasonal gatherings, spontaneous exchange), the directionality (who speaks to whom, through what), and the quality (what kinds of knowing can travel through which channels). At Cobana, healthy information flow requires attending to both formal channels (the partner network, structured meetings, the Blending Regenerative Voices series) and informal ones (meals, walks, thresholds, shared work).",
        thinkers: ["Hutchins","Shannon (origin)","Bohm","Isaacs"],
        tags: ["DSA","communication","community","systems","practice"],
        connections: [
          {to:"dsa-core",label:"DSA circulates through"},
          {to:"comprehension",label:"sustained by"},
          {to:"relational-trust",label:"trust opens flow"},
          {to:"tacit-knowledge",label:"tacit knowledge resists explicit flow"},
          {to:"blending-voices",label:"blending voices as designed flow"},
          {to:"hosting-structure",label:"hosting structures flow"},
          {to:"vocality-dsa",label:"voice as primary medium of flow"},
        ],
        nuances: [
          {thinker:"Formal and informal",note:"One of the recurring insights from distributed cognition research is that informal information flows — the conversation at the meal table, the exchange during shared work, the observation mentioned in passing — are often as important as formal ones. DSA infrastructure at Cobana must design for both, without letting the formal crowd out the informal."},
          {thinker:"Timing",note:"The rhythm of information flow matters as much as its content: daily check-ins serve a different function from weekly gatherings from seasonal reviews. A healthy DSA system has information flows at multiple timescales, each suited to a different kind of awareness — immediate, medium-term, and seasonal."},
        ],
        x:700,y:160,color:"#38bdf8",status:"consolidated",source:"paper",
      },
      {
        id: "more-than-human", term: "More-Than-Human Field",
        definition: "The extension of the DSA system beyond the human community to include the living and non-living systems within which the community is embedded — the Carpathian ecology, the seasonal rhythms of the mountain, the animal populations, the soil microbiome, the river, the weather. In a more-than-human DSA, these are not background but active nodes: sources of information, carriers of awareness, participants in the system's collective sensing. The mountain tells Cobana things that no guest survey can — through phenology, through the behaviour of animals, through the quality of water, through the texture of soil. Learning to receive this information is a practice of attunement as much as of observation.",
        thinkers: ["Haraway","Kohn","Tsing","Ingold","Abram"],
        tags: ["DSA","ecology","more-than-human","place","awareness"],
        connections: [
          {to:"dsa-core",label:"DSA extended into"},
          {to:"distributed-cognition",label:"extends cognition beyond human"},
          {to:"place-knowledge",label:"more-than-human as knowledge source"},
          {to:"seasonal-rhythms",label:"more-than-human temporal structure"},
          {to:"bioregionalism",label:"grounded in"},
          {to:"perception-dsa",label:"perceiving more-than-human signals"},
          {to:"projection",label:"more-than-human signals shape projection"},
        ],
        nuances: [
          {thinker:"Kohn",note:"Eduardo Kohn's How Forests Think argues that the Amazonian forest thinks — not metaphorically but in a genuinely semiotic sense. Signs, selves, and meaning-making are not confined to the human. At Cobana, the Carpathian ecosystem is a semiotic field: its patterns carry meaning that a community attuned to it can read. The more-than-human field is not merely an environment but a co-participant in the community's awareness."},
          {thinker:"Abram",note:"David Abram's The Spell of the Sensuous argues that the animate earth has its own forms of expressiveness — its own voice, in the broadest sense — and that the recovery of perceptual attunement to the more-than-human world is both an ecological and a cultural necessity. DSA that includes the more-than-human field is not adding a dimension to community awareness but restoring a fundamental one."},
        ],
        x:340,y:160,color:"#34d399",status:"consolidated",source:"paper",
      },
      {
        id: "seasonal-rhythms", term: "Seasonal Rhythms",
        definition: "The cyclical temporal structure through which the more-than-human world organises itself — and through which a community embedded in that world can orient its collective awareness. At Cobana, seasonal rhythms are not merely background to community life but a primary structuring force for when the community attends to what. The Romanian folk calendar — Mărțișor, Sânziene, Sângiorz, Sâmedru — encodes accumulated place knowledge of the Carpathian seasonal cycle in cultural form. Attending to seasonal rhythms is a DSA practice: it structures collective projection around a non-human temporality rather than an administrative or market calendar.",
        thinkers: ["Ingold","Berry","Kimmerer","Romanian folk tradition"],
        tags: ["DSA","seasons","time","place","ecology"],
        connections: [
          {to:"more-than-human",label:"seasonal rhythms as more-than-human time"},
          {to:"projection",label:"structures collective projection"},
          {to:"place-knowledge",label:"encoded in"},
          {to:"perception-dsa",label:"attuned to"},
          {to:"bioregionalism",label:"bioregional temporal structure"},
          {to:"hosting-structure",label:"hosting structured by seasons"},
        ],
        nuances: [
          {thinker:"Romanian folk calendar",note:"The Romanian folk calendar — with its markers of Mărțișor (the first day of spring), Sânziene (midsummer), Sângiorz (St George's Day, marking the beginning of pastoral season), and Sâmedru (St Demetrius, marking its end) — encodes millennia of accumulated place knowledge of the Carpathian seasonal cycle. These are not merely cultural traditions but sophisticated DSA tools: they structure collective attention to what the season requires."},
          {thinker:"Against administrative time",note:"The DSA value of seasonal rhythms lies partly in what they resist: the administrative calendar of grant cycles, reporting periods, and fiscal years that structures most organisational life. Seasonal time is qualitatively differentiated — this time is different from that time — rather than homogeneous and interchangeable. A community that attends to seasonal rhythms inhabits time differently from one that attends only to the clock."},
        ],
        x:500,y:540,color:"#facc15",status:"consolidated",source:"paper",
      },
      {
        id: "bioregionalism", term: "Bioregionalism",
        definition: "The political and ecological framework that takes living regions — defined by watershed, soil type, ecological community, and cultural particularity — as the primary unit of human belonging and governance, rather than administrative or national boundaries. Bioregionalism proposes that communities should know and be shaped by the specific place they inhabit: its limits, its gifts, its ecological relationships, its non-human members. At Cobana, bioregionalism frames the Carpathian arc not as backdrop but as the defining context of community identity and practice — the question of what it means to live well in this specific watershed, at this altitude, within this forest-pastoral ecology.",
        thinkers: ["Berg","Snyder","Sale","McGinnis"],
        tags: ["DSA","ecology","place","politics","community"],
        connections: [
          {to:"more-than-human",label:"bioregional framing of"},
          {to:"place-knowledge",label:"bioregional form of"},
          {to:"seasonal-rhythms",label:"seasonal structure of"},
          {to:"distributed-cognition",label:"bioregion as cognitive field"},
        ],
        nuances: [
          {thinker:"Berg",note:"Peter Berg coined the term 'bioregion' and 'reinhabitation' — the practice of learning to live in a place rather than merely on it, of becoming native to a place through sustained relationship and knowledge. Cobana's commitment to the Carpathian bioregion is a practice of reinhabitation in Berg's sense."},
          {thinker:"Governance dimension",note:"Bioregionalism is not only an ecological but a governance framework: it proposes that the appropriate unit for collective decision-making is the living region rather than the administrative district. At Cobana, this means that DSA is bioregional — it attends to the whole living system of the Carpathian arc, not only to the community's immediate territory."},
        ],
        x:300,y:540,color:"#8f7a4a",status:"consolidated",source:"paper",
      },
      {
        id: "hosting-structure", term: "Hosting Structure",
        definition: "The designed rhythms, thresholds, and relational forms through which Cobana receives and accompanies guests — and through which the community's own awareness is continuously renewed. Hosting structure is DSA infrastructure: how a guest arrives (what they are asked to notice, what is made available for perception), how the community gathers (what kinds of shared comprehension are structured), how departure is marked (what is integrated, what is carried forward) all shape the DSA field. At Cobana, hosting structure is not merely a service design but a contemplative practice — an arrangement of time, space, and attention that cultivates the conditions for genuine presence and genuine encounter.",
        thinkers: ["Wheatley","Palmer","Hycner","Goffman"],
        tags: ["DSA","hosting","practice","community","design"],
        connections: [
          {to:"dsa-core",label:"DSA infrastructure"},
          {to:"relational-trust",label:"cultivates"},
          {to:"threshold-awareness",label:"structures"},
          {to:"tacit-knowledge",label:"hosting cultivates tacit attunement"},
          {to:"information-flow",label:"hosting structures flow"},
          {to:"partial-view",label:"guests bring fresh partial views"},
          {to:"blending-voices",label:"hosting creates conditions for"},
        ],
        nuances: [
          {thinker:"Arrival as DSA practice",note:"The moment of arrival is a high-bandwidth DSA moment: the guest arrives with fresh eyes, unhabituated to the community's patterns, and is capable of perceiving things that long-term members have ceased to notice. Hosting structure that attends to arrival — that asks guests what they observe, that creates space for fresh perception to be shared — converts arrival into a collective perceptual renewal."},
          {thinker:"Departure as integration",note:"Departure is equally significant: the moment when what was experienced is integrated, when the guest's partial view is offered back to the community, when what was encountered is named before it is lost. A hosting structure that attends to departure gathers the community's awareness rather than simply releasing participants back into their individual trajectories."},
        ],
        x:700,y:540,color:"#b07a3a",status:"consolidated",source:"paper",
      },
      {
        id: "threshold-awareness", term: "Threshold Awareness",
        definition: "The quality of heightened attention that accompanies crossing a threshold — arriving, departing, transitioning between states of engagement. Thresholds are moments when the habitual organisation of perception loosens: when what has been taken for granted becomes visible again, when new observations become possible. In DSA terms, thresholds are high-bandwidth moments for the circulation of awareness — both the guest arriving with fresh eyes and the long-term member marking a departure renew the community's perceptual field. Threshold awareness is the practice of attending to these moments rather than passing through them unconsciously.",
        thinkers: ["Turner","van Gennep","Heidegger","Winnicott"],
        tags: ["DSA","threshold","awareness","practice","liminality"],
        connections: [
          {to:"hosting-structure",label:"hosting structures thresholds"},
          {to:"perception-dsa",label:"thresholds heighten perception"},
          {to:"partial-view",label:"arrival offers fresh partial view"},
          {to:"place-knowledge",label:"long-term members hold place knowledge"},
          {to:"relational-trust",label:"thresholds require trust"},
          {to:"information-flow",label:"thresholds as high-bandwidth moments"},
        ],
        nuances: [
          {thinker:"Van Gennep / Turner",note:"Arnold van Gennep's rites of passage and Victor Turner's liminality provide the anthropological grounding: thresholds are not merely physical crossing points but transitions between states of being — moments of in-between in which the normal structures of social life are suspended and genuine transformation becomes possible. At Cobana, arrival and departure are threshold rituals in this sense."},
          {thinker:"Habitual perception",note:"The DSA value of threshold awareness lies in its disruption of habituation: long-term members are subject to the gradual dulling of perception that comes with familiarity — things cease to be noticed because they are always there. Thresholds — marked consciously — restore the freshness of perception that habituation suppresses. This is why the guest's arrival is a DSA resource, not merely an operational event."},
        ],
        x:840,y:430,color:"#c084fc",status:"consolidated",source:"paper",
      },
      {
        id: "blending-voices", term: "Blending Regenerative Voices",
        definition: "A structured interview and dialogue series at Cobana, functioning as a relational sensemaking and matchmaking tool grounded in the DSA methodology. The series brings different voices — from partner organisations, from the local and regional context, from the intellectual and practitioner communities associated with Cobana's work — into relation, allowing partial views to be shared, patterns to be identified, and new connections to become possible. It is a deliberate DSA practice: a designed channel through which the community's comprehension of its situation is continuously renewed and deepened. The 'blending' names the aspiration — not the imposition of a unified understanding but the productive mixing of different awarenesses into a richer collective field.",
        thinkers: ["Isaacs","Scharmer","Wheatley"],
        tags: ["DSA","dialogue","community","practice","sensemaking"],
        connections: [
          {to:"dsa-core",label:"deliberate DSA practice"},
          {to:"comprehension",label:"practised through"},
          {to:"information-flow",label:"designed flow channel"},
          {to:"hosting-structure",label:"hosting creates conditions for"},
          {to:"partial-view",label:"brings partial views into relation"},
          {to:"vocality-dsa",label:"practises genuine vocality"},
          {to:"relational-trust",label:"builds through repeated encounter"},
        ],
        nuances: [
          {thinker:"Blending as metaphor",note:"The word 'blending' is deliberately chosen over 'synthesis' or 'integration': blending preserves the distinctiveness of what is mixed while allowing a new complexity to emerge from the mixture. This is the DSA aspiration — not a unified community view that erases difference, but a richer field in which different partial views remain distinguishable while entering into productive relation."},
          {thinker:"Matchmaking dimension",note:"The series also functions as matchmaking: by bringing different people and organisations into conversation, it creates conditions for unexpected connections — people who discover they are working on related questions from different angles, organisations that find unexpected shared ground. This relational generation is itself a DSA outcome."},
        ],
        x:840,y:300,color:"#34d399",status:"consolidated",source:"paper",
      },
      {
        id: "vocality-dsa", term: "Vocality",
        definition: "The claim, developed by Adriana Cavarero, that the voice — the particular, embodied, unrepeatable sound of this person speaking — is the primary medium of human uniqueness and presence. Vocality is distinguished from language: language is a shared system, but the voice is singular. In DSA terms, vocality names what is at stake when partial views are shared: it is not merely that information is transmitted, but that a unique perspective — with its specific timbre, hesitation, emphasis, and embodied situatedness — enters the shared field. Attending to vocality in DSA means designing for genuine speaking and genuine listening, not merely for information exchange.",
        thinkers: ["Cavarero","Merleau-Ponty","Bakhtin"],
        tags: ["DSA","voice","community","presence","dialogue"],
        connections: [
          {to:"dsa-core",label:"DSA requires genuine"},
          {to:"partial-view",label:"each voice carries a partial view"},
          {to:"relational-trust",label:"trust enables genuine voice"},
          {to:"information-flow",label:"voice as primary medium"},
          {to:"blending-voices",label:"practises genuine vocality"},
          {to:"comprehension",label:"vocality deepens comprehension"},
        ],
        nuances: [
          {thinker:"Cavarero",note:"Adriana Cavarero's For More Than One Voice argues that Western philosophy has systematically privileged the logos — the semantic content of speech — over the vocalic: the singular, embodied, unrepeatable quality of this voice speaking. DSA that attends to vocality attends to the whole person speaking, not only to the information they convey."},
          {thinker:"Cross-network",note:"This node extends the Vocality node in the Voice & Vocality vocabulary, where it is developed in full theoretical depth. Here it appears in its specifically DSA application: what does it mean to design a community's information practices so that genuine vocality — singular, embodied, partial — is honoured rather than reduced to data?"},
          {thinker:"Silence and vocality",note:"Vocality includes silence: the pause before speaking, the hesitation that signals something important and unresolved, the moment when someone falls quiet rather than saying what they think they should say. A DSA system that attends to vocality attends to these silences as much as to the words."},
        ],
        x:840,y:540,color:"#e879f9",status:"consolidated",source:"paper",
      },
      {
        id: "situated-knowledge-dsa", term: "Situated Knowledge",
        definition: "Donna Haraway's epistemological argument that all knowledge is produced from a particular location, body, and perspective — there is no view from nowhere, no god-trick of seeing everything from above while claiming to see from nowhere. Situated knowledge is not relativism: some positions are better for seeing certain things than others, and partial perspectives can be linked together to produce something richer than any single view. In DSA terms, situated knowledge is the epistemological foundation of the partial view: every participant's awareness is situated — shaped by their history, position, and relationship to the place — and this situatedness is a resource, not a limitation.",
        thinkers: ["Haraway","Star","Harding","Collins"],
        tags: ["DSA","epistemology","knowledge","place","community"],
        connections: [
          {to:"partial-view",label:"partial view as situated knowledge"},
          {to:"dsa-core",label:"epistemological ground of"},
          {to:"place-knowledge",label:"place knowledge as situated"},
          {to:"vocality-dsa",label:"vocality as situated speaking"},
          {to:"more-than-human",label:"more-than-human knowledge as situated"},
        ],
        nuances: [
          {thinker:"Haraway",note:"In Situated Knowledges (1988), Haraway argues against both relativism (all views are equally valid) and objectivism (there is a view from nowhere). The alternative is situated knowledge: partial, accountable, linked with other partial perspectives. The goal is not a unified view but a richer field constituted by the interaction of genuinely different situated knowledges."},
          {thinker:"Cross-network",note:"This node extends the Situated Knowledge node from the Worlding vocabulary, where Haraway's argument is developed in the context of feminist epistemology and multispecies thinking. Here it appears in its DSA application: how does a community design its practices so that the situatedness of each member's knowledge is honoured and linked rather than erased?"},
        ],
        x:500,y:160,color:"#818cf8",status:"consolidated",source:"paper",
      },
    ],
  };
