// Voice & Vocality vocabulary
// Auto-extracted from semantic-network.jsx

export const metaNetwork = {
    id: "meta", label: "Voice & Vocality",
    subtitle: "A Meta-Vocabulary — The Living Event of Expression and World-Making",
    accent: "#e879f9", storageKey: "semantic-network-meta",
    initialNodes: [
      {
        id: "voice", term: "Voice",
        definition: "The living event of the body becoming expressive — breath shaped into sound, the self opening onto a world and the world being called into a particular shape by that opening. Voice is not a vehicle for thought that already exists elsewhere; it is the place where thought comes into being. For Merleau-Ponty, speaking is not the translation of a pre-formed inner meaning into outer sound — the voice thinks, and meaning happens in the voicing rather than behind it. Before language as a system, there is voice as an act: irreducibly bodily, irreducibly addressed, always already reaching toward an other. Every vocabulary in this system is a form of voicing — a particular body of expression giving shape to a domain of experience, bringing it into a shared world.",
        thinkers: ["Merleau-Ponty","Cavarero","Ong","Bakhtin","Kristeva"],
        tags: ["voice","ontology","phenomenology","embodiment","worlding"],
        connections: [
          {to:"vocality",label:"expressed through"},
          {to:"silence",label:"emerges from and returns to"},
          {to:"resonance",label:"received as"},
          {to:"performative-idiom-meta",label:"voice as performative act"},
          {to:"imaginal-realism",label:"imagination voiced into being"},
          {to:"poiesis-meta",label:"voice as poietic making"},
        ],
        nuances: [
          {thinker:"Merleau-Ponty",note:"For Merleau-Ponty, the voice is the body's way of being with others before grammar organises that being-with into propositions. Speaking is a gesture — a bodily act that brings something into existence in the shared space between speaker and listener. The orator who is genuinely moved by what they are saying demonstrates this: the body takes over, speech exceeds intention, meaning happens in the voice. The voice of someone we know is immediately recognisable because we hear their body, their way of being in the world — not just their words."},
          {thinker:"Cavarero",note:"Adriana Cavarero's For More Than One Voice (2005) argues that Western philosophy has systematically privileged the semantic content of speech over the uniqueness of the vocalising body. Every voice is singular — no two are identical — and this singularity is not incidental but essential. The voice carries the irreducible who of the speaker, not just the what. Cavarero calls this the vocalic: the dimension of speech that is not yet language but more than noise — the individual body sounding itself into a shared world."},
          {thinker:"Ong",note:"Walter Ong's Orality and Literacy shows that in primary oral cultures — where there is no writing — the word is understood as event and power, not as information. The spoken word is alive in a way the written word is not: it happens, reverberates, and cannot be retrieved. Writing has made us forget this fundamental aliveness, treating language as a container for meaning rather than as a living vocal act. The voice is the original, and writing is always a secondary inscription of what was first sounded."},
          {thinker:"Bakhtin",note:"For Bakhtin, every utterance is inhabited by other voices — every word carries the accents, intentions, and histories of all its previous uses. Voice is irreducibly dialogical: you cannot speak without responding to voices that came before and anticipating voices that will respond. The living word is always the word in dialogue — which is why a vocabulary is never the possession of one speaker but a shared medium that many voices have shaped and continue to shape."},
          {thinker:"This vocabulary",note:"This vocabulary is an introduction to all the others in this system. Each subsequent vocabulary — on livelihoods, on worlding, on Vienna, on movement — is a form of voicing: a particular way of giving expression to a domain of experience and thereby bringing it into a shared world. The question this vocabulary poses is not only 'what does language do?' but 'what does it mean to speak at all, to be heard, to resonate, to fall silent?'"},
        ],
        x:500,y:300,color:"#e879f9",status:"consolidated",source:"manual",
      },
      {
        id: "vocality", term: "Vocality",
        definition: "The quality of being voiced — the specific timbre, tone, texture, and rhythm through which a particular being expresses itself in the world. No two voices are identical: vocality is what makes expression irreducibly personal even when the words are shared. It is the dimension of speech that exceeds semantic content — what is carried by how something is said rather than what is said. Vocality is the signature of a living being in language: its accent, its hesitations, its particular way of rising and falling, its characteristic silences. A community has vocality as much as an individual — a way of speaking together that is recognisably its own.",
        thinkers: ["Cavarero","Barthes","Kristeva","Merleau-Ponty"],
        tags: ["voice","phenomenology","embodiment","identity","expression"],
        connections: [
          {to:"voice",label:"quality of"},
          {to:"silence",label:"defined against and through"},
          {to:"resonance",label:"what resonates is vocality"},
          {to:"poiesis-meta",label:"vocality as poietic signature"},
        ],
        nuances: [
          {thinker:"Cavarero",note:"Cavarero's vocalic is the dimension of speech that philosophy has consistently suppressed in favour of the logos — the semantic, the rational, the universal. Vocality restores what the logos erases: the singularity of the speaking body, the fact that every utterance comes from a specific throat in a specific body at a specific moment. This singularity is not a limitation on meaning but its living source."},
          {thinker:"Barthes",note:"Roland Barthes's essay 'The Grain of the Voice' distinguishes between the pheno-song (what is communicated — melody, words, expression) and the geno-song (the body in the voice — its grain, its materiality, the way the tongue and throat and breath shape sound). Vocality corresponds to what Barthes calls the grain: the erotic, irreducible presence of the body in the act of singing or speaking."},
          {thinker:"Community vocality",note:"A research vocabulary has vocality in this sense — a particular way of speaking that is recognisable as belonging to a tradition, a community, a form of inquiry. The vocabulary of phenomenology sounds different from the vocabulary of economics sounds different from the vocabulary of indigenous knowledge. These differences are not merely terminological but vocalic: they carry different rhythms, different silences, different ways of reaching toward what is being said."},
        ],
        x:700,y:200,color:"#c084fc",status:"consolidated",source:"manual",
      },
      {
        id: "silence", term: "Silence",
        definition: "Not the absence of voice but its ground and its horizon — the medium through which voice becomes meaningful. Silence is prior to speech and returns after it; it is what voice emerges from and what it points toward when it reaches the edge of what can be said. In the contemplative traditions — Benedictine, Quaker, Zen — silence is not empty but full: a mode of presence, attention, and receptivity that is more fundamental than speech. The Rule of Benedict treats silence as a practice and a disposition: the monk who is learning to listen before speaking is learning something about the nature of all genuine communication. Silence is also the form that the Unsayable takes in practice — not the abstract limit of language but the lived, cultivated, intentional refusal to fill every space with words.",
        thinkers: ["Cage","Merton","Wittgenstein","Quaker tradition","Benedict"],
        tags: ["voice","silence","contemplative","ontology","practice"],
        connections: [
          {to:"voice",label:"ground and horizon of"},
          {to:"vocality",label:"defined against and through"},
          {to:"resonance",label:"silence as resonant space"},
          {to:"poiesis-meta",label:"silence as condition of poiesis"},
        ],
        nuances: [
          {thinker:"Cage",note:"John Cage's 4'33\" (1952) is the most radical artistic statement of silence as a positive phenomenon: the piece consists of a performer making no intentional sounds for four minutes and thirty-three seconds, and what is heard is the ambient sound of the environment — the audience's breathing, the traffic outside, the settling of the building. Cage shows that silence is never empty; it is always full of what was already there, waiting to be heard."},
          {thinker:"Merton",note:"Thomas Merton's writings on contemplative silence — particularly in The Silent Life and Contemplative Prayer — treat silence not as the absence of communication but as a mode of presence more intimate than speech. In silence, the monk is not isolated but most fully in relation: to God, to the community, to the created world. Silence is where the deepest listening happens."},
          {thinker:"Quaker tradition",note:"In Quaker worship, silence is the primary medium: the meeting waits in gathered silence until someone is moved to speak, and what is spoken emerges from that silence and returns to it. This is a governance of voice through silence — authority rests not with a designated speaker but with the quality of attentiveness that sustained silence makes possible. The Quaker meeting is perhaps the most developed institutional form of silence as a communal practice."},
          {thinker:"Wittgenstein",note:"The final proposition of the Tractatus — 'Whereof one cannot speak, thereof one must be silent' — is often misread as a dismissal. But it points toward something more generous: silence is the appropriate response to what exceeds language, the ethical gesture of not forcing words onto what words cannot hold. Silence, in this sense, is the most honest form of acknowledgment."},
        ],
        x:300,y:200,color:"#818cf8",status:"consolidated",source:"manual",
      },
      {
        id: "resonance", term: "Resonance",
        definition: "What happens when voice meets a world that receives it — and is changed by that receiving. Resonance is both acoustic (the room that gives voice its particular character, the body that vibrates in response to sound) and relational (the other whose response transforms what was said, the community whose reception shapes what can be voiced). Hartmut Rosa's sociology of resonance names something the contemplative traditions have always known: the experience of genuine response — of being heard, of having one's voice land somewhere and return changed — is not incidental to human life but one of its most fundamental needs. A vocabulary resonates when it is not merely understood but felt: when it changes the one who uses it, when it opens something that was closed, when it vibrates in the body as well as the mind.",
        thinkers: ["Rosa","Merleau-Ponty","Cavarero","Heidegger"],
        tags: ["voice","relation","phenomenology","community","reception"],
        connections: [
          {to:"voice",label:"voice received as"},
          {to:"vocality",label:"what resonates is the vocalic"},
          {to:"silence",label:"silence as resonant space"},
        ],
        nuances: [
          {thinker:"Rosa",note:"Hartmut Rosa's Resonance: A Sociology of Our Relationship to the World (2019) argues that the fundamental problem of modern life is not alienation in the Marxist sense but a-resonance: the experience of a world that does not respond, that does not speak back, that leaves the self unaffected and untransformed. Resonance, by contrast, is the experience of being genuinely touched by what one encounters — and of genuinely affecting it in return. Rosa identifies art, religion, nature, and love as the primary domains where resonance remains possible."},
          {thinker:"Acoustic resonance",note:"The acoustic dimension of resonance is not merely metaphorical. A voice resonates in a space — a cathedral, a forest clearing, a small room — and the space shapes the voice even as the voice fills the space. Gregorian chant was composed for stone vaults; the Quaker meeting house is built for gathered stillness. The architecture of contemplative spaces is a theory of resonance made material — an attempt to create the conditions under which voice and silence can meet in their fullest forms."},
          {thinker:"Vocabulary resonance",note:"A vocabulary resonates when its terms are not merely applied but inhabited — when using them changes how one sees, feels, and acts. The test of a vocabulary is not its logical coherence but its resonance: does it open something? Does it allow something to be said that could not be said before? Does it change the one who uses it? These vocabularies aim at resonance rather than comprehensiveness."},
        ],
        x:500,y:450,color:"#f472b6",status:"consolidated",source:"manual",
      },
      {
        id: "performative-idiom-meta", term: "Performative Idiom",
        definition: "The methodological and ontological shift — developed by Pickering but with roots running through Austin's speech act theory, Wittgenstein's language games, and the enactivist tradition — from asking what language and practice represent to asking what they do. In the performative idiom, a vocabulary is not a set of descriptions of a pre-given world but a set of practices for bringing certain worlds into being. Science and shamanism, for instance, are not competing representations of one nature but different ways of engaging with a lively world. Applied to voice: every act of voicing is performative — it does not describe what is already there but enacts what becomes real in and through the saying.",
        thinkers: ["Pickering","Austin","Wittgenstein","Butler","Haraway"],
        tags: ["voice","epistemology","ontology","practice","STS"],
        connections: [
          {to:"voice",label:"voice as performative act"},
          {to:"imaginal-realism",label:"ontological parallel"},
          {to:"poiesis-meta",label:"what performance is grounded in"},
          {to:"resonance",label:"performance received as resonance"},
        ],
        nuances: [
          {thinker:"Pickering",note:"In The Mangle of Practice, Pickering argues that scientific knowledge is not discovered or constructed but mangled — shaped in the open-ended, unpredictable dance between human intention and material resistance. The performative idiom names the shift that makes this visible: from asking 'is this true?' to asking 'what does this do?' Applied to voice: the question is not 'does this voice accurately represent what I mean?' but 'what does this voice bring into being?'"},
          {thinker:"Austin",note:"J.L. Austin's How to Do Things with Words (1962) shows that many utterances do not describe but enact: 'I promise', 'I declare', 'I name this ship' are not true or false but felicitous or infelicitous — they succeed or fail as acts. This is voice understood as action: the voice that marries, that condemns, that blesses, that curses. Performativity is voice at its most consequential."},
          {thinker:"Butler",note:"Judith Butler extends the performative idiom to identity and the body: who we are is constituted through repeated performative acts rather than expressed by them. The voice that says 'I' brings into being the self it names — not once but continuously, through the repeated act of speaking oneself into existence in relation to others."},
        ],
        x:300,y:420,color:"#f472b6",status:"consolidated",source:"manual",
      },
      {
        id: "imaginal-realism", term: "Imaginal Realism",
        definition: "The claim that imagination is not the opposite of reality but one of its primary modes of constitution — that through voice, metaphor, story, and the social imaginary, worlds are genuinely brought into being rather than merely represented or fantasised. What a community voices about itself — its myths, its self-descriptions, its inherited metaphors — is not ornamental but ontological: it makes the world what it is for those who inhabit it. Drawing on Castoriadis's account of the social imaginary as the instituting creative force of society, imaginal realism insists that to change what is voiced is to change the world, not merely to change one's description of it.",
        thinkers: ["Castoriadis","Bachelard","Corbin","Hillman","Ricoeur"],
        tags: ["voice","imagination","ontology","worlding","creativity"],
        connections: [
          {to:"voice",label:"imagination voiced into being"},
          {to:"performative-idiom-meta",label:"ontological parallel"},
          {to:"poiesis-meta",label:"imagination as poiesis"},
          {to:"resonance",label:"imaginal voice that resonates"},
          {to:"grounding-imaginal",label:"recovered through"},
          {to:"misplacing-imaginal",label:"obscured by"},
        ],
        nuances: [
          {thinker:"Castoriadis",note:"For Castoriadis, the social imaginary is not a collection of images or representations but the instituting creative force of society — the radical imagination that produces new meanings, institutions, and forms of life. The imaginary is real not despite being imagined but because it is imagined and voiced: it is what makes a society a society. To voice a new imaginary is to begin making a new world."},
          {thinker:"Bachelard",note:"Gaston Bachelard's Poetics of Space and his studies of elemental imagination show how the images through which we inhabit the world — house, nest, fire, water — are not neutral descriptions but structuring forces that shape what we can feel, think, and do. Imaginal realism at its most phenomenologically rich: the voiced image makes the world."},
          {thinker:"Ricoeur",note:"Paul Ricoeur's theory of narrative identity: who I am is constituted by the stories told about me and by me. Identity is not a property I have but a narrative I inhabit — and narratives, like all language, are both received and voiced. The self is a voiced story, always being revised in the telling."},
        ],
        x:700,y:420,color:"#c084fc",status:"consolidated",source:"manual",
      },
      {
        id: "grounding-imaginal", term: "Grounding the Imaginal",
        definition: "Both a philosophical recovery and a practice. Philosophically: recognising that imagination is not one faculty among others but the foundational process from which subjectivity itself emerges — the ground of selfhood rather than a capacity the self possesses. Practically: the discipline of bringing imaginative activity into relationship with specific place, specific community, specific embodied and seasonal life. An image that is not grounded drifts into abstraction or fantasy — it loses its weight and its claim on the real. An image grounded in a particular landscape, a particular community's history, a particular season, carries a different quality: it participates in the reality of what it images rather than merely representing it. Grounding the imaginal is the practice of keeping this specificity alive — refusing the drift toward the generic, the placeless, the disembodied.",
        thinkers: ["Corbin","Bachelard","Hillman","Castoriadis","Heidegger"],
        tags: ["voice","imagination","place","practice","ontology"],
        connections: [
          {to:"imaginal-realism",label:"recovers"},
          {to:"misplacing-imaginal",label:"corrects"},
          {to:"voice",label:"grounded voice as imaginal practice"},
          {to:"silence",label:"silence as ground of imaginal"},
          {to:"resonance",label:"grounded imaginal resonates"},
          {to:"poiesis-meta",label:"grounded poiesis"},
        ],
        nuances: [
          {thinker:"Corbin",note:"Henry Corbin's mundus imaginalis — developed through his study of Islamic mystical philosophy, particularly Ibn Arabi and Suhrawardi — names an ontologically real intermediate world between the purely sensory and the purely intelligible. The imaginal world is not a realm of subjective fantasy but a world you enter and encounter, with its own geography, its own inhabitants, its own events. Grounding the imaginal, in Corbin's sense, means taking this world seriously as a domain of genuine knowledge and genuine encounter — not reducing it to psychology or poetry."},
          {thinker:"Bachelard",note:"Bachelard's elemental images — fire, water, earth, air — are always specific: this fire, this corner of the house, this quality of water. The poetic image for Bachelard is irreducibly singular and irreducibly present: it cannot be paraphrased or generalised without losing what makes it an image rather than a concept. Grounding the imaginal means maintaining this singularity — keeping images anchored in their specific elemental and phenomenological territory."},
          {thinker:"Place dimension",note:"The practice dimension of grounding the imaginal connects directly to Re-Rooting as a project: the imagination that is grounded in a specific place — its seasonal rhythms, its ecological particularity, its community's living history — is imagination in its fullest sense. The imaginal capacity does not float free of where it is exercised; it is shaped by and shapes the specific terrain it inhabits. A community's imaginal life is always a local imaginal life, even when it draws on universal themes."},
          {thinker:"Heidegger",note:"Heidegger's reading of Kant's transcendental imagination as the common root of sensibility and understanding — more primordial than either faculty — supports the grounding move: if imagination is the ground of subjectivity rather than one of its faculties, then grounding the imaginal means returning to the source rather than exercising a capacity. This is imagination understood from below rather than from above."},
        ],
        x:840,y:300,color:"#a78bfa",status:"consolidated",source:"manual",
      },
      {
        id: "misplacing-imaginal", term: "Misplacing the Imaginal",
        definition: "The historical process by which imagination was reduced from a foundational creative ground to one cognitive faculty among others — a capacity the subject possesses and exercises rather than the process from which subjectivity itself emerges. The misplacement is simultaneously a deterritorialization: imagination is lifted from its territory in the real — from the world's own creativity, from place, from community, from the more-than-human — and reterritorialized inside the subject as a rule-governed, instrumental operation serving other ends. Once misplaced, imagination becomes primarily associated with loss and lack: it produces representations of what is absent, compensates for what cannot be directly experienced, fills gaps left by the real rather than participating in the real's own creative process.",
        thinkers: ["Kant","Coleridge","Sartre","Castoriadis (critique)","Heidegger (recovery)"],
        tags: ["voice","imagination","critique","modernity","history"],
        connections: [
          {to:"imaginal-realism",label:"obscures"},
          {to:"grounding-imaginal",label:"what grounding corrects"},
          {to:"misplacing-imaginal",label:"self-referential"},
          {to:"poiesis-meta",label:"misplacement suppresses poiesis"},
          {to:"silence",label:"misplacement fills silence that should remain"},
        ],
        nuances: [
          {thinker:"Kant",note:"Kant's productive imagination (Einbildungskraft) in the Critique of Pure Reason is already a partially misplaced imaginal: it is creative in the sense that it generates the schemata that make experience possible, but it operates according to fixed rules and in service of the understanding. It mediates between sensibility and understanding rather than grounding both. Heidegger argues that Kant himself was on the verge of recognising the imagination as the common root of both — and then pulled back, subordinating it to the understanding in the second edition. The suppression is visible in the text."},
          {thinker:"Faculty psychology",note:"The deepest misplacement occurs when imagination becomes one faculty among others in a psychology of cognitive capacities — alongside memory, perception, reasoning, and will. Once sorted into this taxonomy, imagination loses its foundational character: it becomes the capacity for mental imagery, for creative combination, for counterfactual thinking. These are real capacities, but they are the surface effects of something more primordial that the faculty model cannot see."},
          {thinker:"Deterritorialization",note:"The misplacement of the imaginal is a deterritorialization in Deleuze and Guattari's sense: imagination is lifted from its territory in the real — from the world's own creativity, from the living imaginal life of specific communities in specific places — and reterritorialized as a private, inner, subjective capacity. This reterritorialization has the structure of enclosure: what was common, shared, and worldly becomes individual, interior, and portable. The recovery of the imaginal requires a corresponding reterritorialization — a return to the territory from which it was lifted."},
          {thinker:"Lack and loss",note:"Once imagination is understood as the capacity to represent what is absent — to produce images of what is not here, not real, not present — it becomes structurally associated with lack. The imagined is what is not real; imagination compensates for what reality withholds. This is the deepest consequence of the misplacement: the imaginal loses its claim to the real and becomes the medium of the unreal. Recovering imaginal realism means inverting this: the imaginal is not the realm of the absent but the depth dimension of the present."},
          {thinker:"Castoriadis",note:"Castoriadis's critique of the Western philosophical tradition's treatment of imagination is the most sustained account of the misplacement: from Aristotle through Kant, imagination is consistently subordinated to reason, to representation, to the already-determined. The radical imagination — which creates genuinely new forms ex nihilo — is systematically unthought because it cannot be assimilated to any deterministic or representational framework. The misplacement is not accidental but structural: a tradition built on the primacy of the logos cannot think the imagination in its full creative power."},
        ],
        x:840,y:540,color:"#f87171",status:"provisional",source:"manual",
      },
      {
        id: "poiesis-meta", term: "Poiesis",
        definition: "From the Greek: making, bringing-forth, production in the fullest sense. Heidegger recovers the term to name a mode of bringing-forth that lets things come into presence rather than forcing them to yield calculable results. Applied to voice: poiesis is what voice does when it is at its most alive — not transmitting a pre-formed message but letting something come forth that could not have been anticipated before the speaking. The poem is the paradigm case: language in which each word opens the next, in which the meaning arrives in the making rather than being deposited there in advance. A vocabulary is a poietic act — it makes a world available that was not available before the voicing.",
        thinkers: ["Heidegger","Aristotle","Arendt","Ong"],
        tags: ["voice","ontology","making","creativity","philosophy"],
        connections: [
          {to:"voice",label:"voice as poietic making"},
          {to:"silence",label:"silence as condition of poiesis"},
          {to:"performative-idiom-meta",label:"performance grounded in poiesis"},
          {to:"imaginal-realism",label:"imagination as poiesis"},
          {to:"sounding",label:"poiesis as sounding"},
        ],
        nuances: [
          {thinker:"Heidegger",note:"In The Question Concerning Technology, Heidegger distinguishes poiesis from the modern technological mode of Herausforderung — challenging-forth, forcing nature to yield calculable results. Poiesis, by contrast, lets beings come forth into their own presence. This is the model for what voice does at its best: not extracting a pre-formed meaning but letting something emerge that shapes itself in the voicing."},
          {thinker:"Aristotle",note:"For Aristotle, poiesis is one of three fundamental human activities alongside praxis (action) and theoria (contemplation). It is the activity of making something that has its telos outside itself — the poem, the pot, the building. Applied to voice: the poietic utterance produces something that outlasts the voicing — a song, a story, a vocabulary — that others can inhabit."},
          {thinker:"Ong",note:"Ong's account of oral poetics shows how in cultures of primary orality, making and voicing are inseparable: the poet is the one who voices the tradition into existence for this community at this moment, drawing on inherited formulas but making something new in the living performance. Poiesis is voice at its most generative."},
        ],
        x:500,y:160,color:"#fb923c",status:"consolidated",source:"manual",
      },
      {
        id: "sounding", term: "Sounding",
        definition: "A suggested node — not yet fully integrated. Sounding names the act of giving voice to what has not yet found its form — the exploratory, tentative, reaching quality of voice when it is feeling its way toward something rather than delivering something already known. To sound something out is to test it in the world, to hear how it lands, to let the response shape what is being said. Sounding is voice in its most genuinely open mode: not performance (which implies a degree of mastery) and not silence (which withholds), but the middle space of genuine inquiry where the voice is both making and finding at once.",
        thinkers: ["suggested","Merleau-Ponty (resonance)","Ingold (resonance)"],
        tags: ["voice","inquiry","practice","becoming","suggested"],
        connections: [
          {to:"voice",label:"voice in its exploratory mode"},
          {to:"poiesis-meta",label:"sounding as poiesis"},
          {to:"silence",label:"emerges from silence"},
          {to:"resonance",label:"sounding toward resonance"},
        ],
        nuances: [
          {thinker:"Status",note:"This node is marked as suggested — it is present as an open direction rather than a consolidated term. It may be developed further, merged with another node, or retired as the vocabulary grows. It sits at the edge of the vocabulary pointing toward something not yet fully named."},
          {thinker:"Possible directions",note:"Sounding could develop toward: the phenomenology of exploratory speech (Merleau-Ponty on the orator who does not know what they will say), Ingold's account of following a line of inquiry without a predetermined destination, or the musical sense of sounding as the full resonance of an instrument or voice finding its range. Any of these directions would deepen what is here gestured at."},
        ],
        x:500,y:540,color:"#94a3b8",status:"provisional",source:"manual",
      },
    ],
  };
