// Movement & Desire vocabulary
// Auto-extracted from semantic-network.jsx

export const movementNetwork = {
    id: "movement", label: "Movement & Desire",
    subtitle: "Ingold, Deleuze — Wayfaring, Flow & the Freedom to Move",
    accent: "#fb923c", storageKey: "semantic-network-movement",
    initialNodes: [
      {
        id: "wayfaring", term: "Wayfaring",
        definition: "Tim Ingold's alternative to the modern figure of the transported passenger or the navigating tourist: the wayfarer does not move from point A to point B across a pre-existing surface but grows along a line, accumulating knowledge, relationship, and self through the act of moving itself. The path is not a route planned and then executed — it is a trail laid down in the walking, a thread drawn through a world that is itself in motion. Wayfaring is movement as dwelling: you are not displaced from home by moving but constituted through movement as a being who belongs to the paths you have walked.",
        thinkers: ["Ingold","Thoreau","Snyder","Benjamin"],
        tags: ["movement","place","practice","embodiment","becoming"],
        connections: [
          {to:"lines-of-movement",label:"traced through"},
          {to:"moving-freely",label:"fullest expression of"},
          {to:"lockstep",label:"opposed to"},
          {to:"derive",label:"urban form of"},
          {to:"pilgrimage",label:"purposive form of"},
          {to:"flows-of-desire",label:"desire animates"},
        ],
        nuances: [
          {thinker:"Ingold",note:"In Lines (2007) and Being Alive (2011), Ingold develops wayfaring as the primary mode of human existence — not a special activity but the basic form of being-in-the-world. The wayfarer's knowledge is not a map held in the head but a skill accumulated in the body through the practice of moving along. To know a place is to have walked it, not to have represented it."},
          {thinker:"Thoreau",note:"Thoreau's Walking (1862) is the classic literary expression of wayfaring: the walk as a practice of attention, freedom, and self-formation. 'I think that I cannot preserve my health and spirits unless I spend four hours a day at least — and it is commonly more than that — sauntering through the woods and over the hills and fields.' The walk is not exercise but a form of life."},
          {thinker:"Benjamin",note:"Walter Benjamin's figure of the flâneur — the urban walker who moves through the city without destination, reading it as a text — is a wayfaring figure, though one specific to the modern metropolis. Benjamin's unfinished Arcades Project is itself a form of wayfaring: a text that moves through material without arriving at a conclusion."},
          {thinker:"Cross-network",note:"Wayfaring connects to Re-Inhabitation in the Livelihoods vocabulary — both name a mode of knowing a place through sustained bodily engagement — and to Dwelling in the Worlding vocabulary. Where dwelling emphasises staying, wayfaring emphasises moving: both are opposed to the tourist's or the manager's relationship to place, which treats it as backdrop rather than medium."},
        ],
        x:300,y:200,color:"#fb923c",status:"consolidated",source:"manual",
      },
      {
        id: "lines-of-movement", term: "Lines of Movement",
        definition: "From Ingold's Lines: a distinction between two fundamentally different kinds of line that organise movement in the world. Connective lines join points — they are the lines of transport, logistics, the grid, the flight path — the traveler moves along them as a passenger, without accumulating knowledge of the terrain between nodes. Wayfaring lines are grown through movement — they are trails, paths, desire lines worn into the ground by repeated passage. Connective lines are imposed on the world; wayfaring lines emerge from it. The progressive replacement of wayfaring lines by connective lines is one of the characteristic movements of modernity.",
        thinkers: ["Ingold"],
        tags: ["movement","space","modernity","practice","place"],
        connections: [
          {to:"wayfaring",label:"traced through"},
          {to:"lockstep",label:"connective lines produce"},
          {to:"moving-freely",label:"wayfaring lines enable"},
          {to:"flows-of-desire",label:"desire carves wayfaring lines"},
        ],
        nuances: [
          {thinker:"Ingold",note:"The contrast between transport and wayfaring lines is also a contrast between two kinds of knowledge: the transport passenger knows origin and destination; the wayfarer knows the path. Modern infrastructure has made us increasingly passengers — we move faster, further, and know less about where we are."},
          {thinker:"Desire lines",note:"In urban design, 'desire lines' are the informal paths worn by people ignoring planned routes — the diagonal across a lawn, the shortcut through a gap in a fence. They are the literal inscription of wayfaring desire onto a surface that was designed for connective movement. Landscape architects increasingly incorporate them, recognising that they carry real knowledge about how people actually want to move."},
        ],
        x:160,y:340,color:"#f59e0b",status:"consolidated",source:"manual",
      },
      {
        id: "flows-of-desire", term: "Flows of Desire",
        definition: "From Deleuze and Guattari's Anti-Oedipus and A Thousand Plateaus: desire understood not as lack — the Freudian and romantic model, in which desire is wanting what you do not have — but as positive production, as flow. Desire flows, connects, assembles, breaks apart and reconnects: it is the energy by which new configurations of life, relationship, and world are assembled. Movement motivated by desire-as-flow is fundamentally different from movement motivated by need, obligation, or the satisfaction of lack. It is movement that produces rather than merely reaches: the journey changes the destination by the time it arrives.",
        thinkers: ["Deleuze","Guattari","Spinoza (origin)","Nietzsche (resonance)"],
        tags: ["movement","desire","Deleuze","ontology","becoming"],
        connections: [
          {to:"wayfaring",label:"animates"},
          {to:"moving-freely",label:"what free movement feels like"},
          {to:"lockstep",label:"what blockage of feels like"},
          {to:"derive",label:"tactical expression of"},
          {to:"lines-of-movement",label:"desire carves wayfaring lines"},
          {to:"deterritorialization",label:"desire as deterritorializing force"},
        ],
        nuances: [
          {thinker:"Deleuze & Guattari",note:"Anti-Oedipus (1972) opens with the claim that desire is not theatrical — it does not represent, it produces. Desire is a machine: it connects to other machines (an eye-machine coupled to a light-machine, a mouth-machine coupled to a breast-machine), and these connections produce flows. The question is never 'what does desire mean?' but 'what does desire do? what does it connect? what does it produce?'"},
          {thinker:"Against lack",note:"The model of desire as lack — you desire what you don't have, and satisfaction extinguishes desire — is both philosophically impoverished and politically domesticating: it makes desire reactive, dependent on an absent object, manageable by supplying or withholding that object. Desire as flow is irreducibly active: it does not wait to be given, it moves, it makes."},
          {thinker:"Spinoza",note:"The philosophical root of desire-as-flow is Spinoza's conatus — the drive by which each being strives to persist and increase in its power of acting. For Spinoza, desire is not a failing or a lack but the very essence of the human being: we are our desires, and the question is whether they expand or contract our capacity to act and relate."},
          {thinker:"Cross-network",note:"Flows of desire connect to Deterritorialization in the Livelihoods vocabulary — desire is one of the primary deterritorializing forces, breaking established configurations open — and to Worldly Desire in the Worlding vocabulary, which names the specific form of desire that orients a being toward participation in a world."},
        ],
        x:500,y:300,color:"#c084fc",status:"consolidated",source:"manual",
      },
      {
        id: "moving-freely", term: "Moving Freely",
        definition: "Not the liberal freedom of choice — the freedom to select among available routes in a market of destinations — but the phenomenological experience of movement that feels like a genuine expression of oneself in relation to a world that receives it. Moving freely is movement without undue constraint, but more than that: it is movement in which the mover feels themselves to be genuinely in motion, genuinely going somewhere that matters, genuinely shaped by and shaping the terrain they pass through. It has a relational dimension — you move freely with others, in a world that makes your movement meaningful — and a worldly dimension — free movement is movement that leaves a trace, that matters to the world you move through.",
        thinkers: ["Ingold","Deleuze","Arendt","Weil"],
        tags: ["movement","freedom","phenomenology","ethics","embodiment"],
        connections: [
          {to:"wayfaring",label:"fullest expression of"},
          {to:"flows-of-desire",label:"desire flowing without blockage"},
          {to:"lockstep",label:"opposed to"},
          {to:"derive",label:"deliberate practice of"},
          {to:"pilgrimage",label:"purposive form of"},
        ],
        nuances: [
          {thinker:"Against optionality",note:"Liberal political philosophy tends to equate freedom of movement with the availability of options: you are free to move if no one prevents you. But this formal freedom is compatible with a profound phenomenological unfreedom — the experience of moving through airports, highways, and managed urban spaces as a passenger in a system you did not design and cannot meaningfully alter. Moving freely requires more than the absence of prohibition."},
          {thinker:"Relational dimension",note:"Moving freely is always moving with — with others, with a landscape, with a history, with a body that has its own desires and capacities. The isolated individual exercising 'freedom of movement' in an abstract space is not moving freely in this sense; they are moving through a non-place. Free movement is embedded movement: it requires a world to move through that has texture, resistance, invitation."},
          {thinker:"Weil",note:"Simone Weil's concept of affliction — the condition of those whose capacity to act and move has been crushed — is the negative image of moving freely. Affliction is not merely suffering but the destruction of the capacity to initiate, to go somewhere, to leave a mark. Moving freely is the condition of the unaflicted person — not the absence of difficulty but the presence of genuine agency in relation to a world."},
          {thinker:"Arendt",note:"Arendt's concept of action — the capacity to begin something new in the public realm — is closely related to moving freely: both name the experience of genuine initiation, of being the source of a movement rather than a passenger in someone else's. Action for Arendt requires a public space in which it can appear and be received; moving freely requires a world in which movement matters."},
        ],
        x:500,y:160,color:"#4ade80",status:"consolidated",source:"manual",
      },
      {
        id: "lockstep", term: "Lockstep",
        definition: "The specific quality of movement under integrated world capitalism: movement that is formally free — you can go anywhere, the world has never been more connected — but phenomenologically constrained, structured by rhythms, routes, and timings that the mover did not set and cannot meaningfully alter. In lockstep you move, but you move in time with a beat that precedes you: the departure schedule, the supply chain, the career ladder, the tourist itinerary, the daily commute. Lockstep is the experiential correlate of Augé's non-place and Baudrillard's simulacrum: movement that is ubiquitous and evacuated of genuine meaning simultaneously.",
        thinkers: ["Augé","Baudrillard","Virilio","Weil"],
        tags: ["movement","modernity","critique","capitalism","phenomenology"],
        connections: [
          {to:"wayfaring",label:"opposite of"},
          {to:"moving-freely",label:"opposite of"},
          {to:"flows-of-desire",label:"blockage of"},
          {to:"lines-of-movement",label:"connective lines produce"},
          {to:"non-place",label:"spatial environment of"},
          {to:"deterritorialization",label:"produces without reterritorialization"},
        ],
        nuances: [
          {thinker:"Etymology",note:"Lockstep originally described a military marching formation in which prisoners or soldiers move in tight single file, each person's step constrained by the person immediately ahead. The image captures something essential: in lockstep you are moving, your legs are working, but the movement is not yours. The form of freedom (locomotion) is present; the substance (self-directed movement through a world) is absent."},
          {thinker:"Virilio",note:"Paul Virilio's dromology — the study of speed as a political phenomenon — provides the theoretical context for lockstep: the acceleration of movement in modernity has not produced freedom but a new form of constraint, in which the fastest route is the only route, and the capacity to slow down or stop or go sideways is progressively eliminated."},
          {thinker:"Weil",note:"Weil's analysis of industrial labour — in which the worker's movements are determined by the machine rather than by the worker's own judgment and skill — is an early account of lockstep. The factory worker moves, but the movement is not expressive of their capacity; it is the machine's requirement that the body fulfils. Weil saw this as a form of affliction: the body in motion but the person absent."},
          {thinker:"Cross-network",note:"Lockstep connects to Nowhere-Everywhereness in the Non-Places vocabulary — both name conditions in which formal movement is accompanied by existential stasis — and to Uprootedness in the Livelihoods vocabulary: lockstep movement is the kind of movement that uprootedness produces, and that in turn deepens uprootedness."},
        ],
        x:700,y:200,color:"#f87171",status:"consolidated",source:"manual",
      },
      {
        id: "derive", term: "Dérive",
        definition: "From the Situationist International, developed primarily by Guy Debord: a practice of unplanned, desire-guided movement through urban space, allowing oneself to be drawn by the psychogeographic pull of the terrain — the quality of architecture, the feel of a neighbourhood, the invitation of a staircase or an alley — rather than by destination, purpose, or habit. The dérive is a deliberate practice of moving freely in the city: a form of research into the emotional and social textures of urban space that official maps and planned routes suppress. It is both a method and a practice of freedom.",
        thinkers: ["Debord","Vaneigem","Situationist International"],
        tags: ["movement","urban","practice","desire","freedom"],
        connections: [
          {to:"wayfaring",label:"urban form of"},
          {to:"moving-freely",label:"deliberate practice of"},
          {to:"flows-of-desire",label:"desire-guided movement"},
          {to:"lockstep",label:"deliberate refusal of"},
          {to:"non-place",label:"what dérive resists"},
        ],
        nuances: [
          {thinker:"Debord",note:"In Theory of the Dérive (1956), Debord describes the practice as 'a technique of rapid passage through varied ambiances' — but what makes it a technique rather than a stroll is its attentiveness: the dériveur is not simply wandering but attending to the affective quality of the terrain, mapping the psychogeographic landscape that underlies the official one. The dérive produces knowledge that no map contains."},
          {thinker:"Psychogeography",note:"The Situationists coined 'psychogeography' for the study of how the urban environment affects the emotions and behaviour of those who move through it. A psychogeographic map of a city looks nothing like a street map: it shows zones of attraction and repulsion, currents and eddies, places that invite lingering and places that accelerate movement. The dérive is the method by which such maps are made."},
          {thinker:"Contemporary relevance",note:"The dérive has been taken up in contemporary urban practice, from architectural research to community art to activist mapping. Its core insight — that the designed city suppresses certain kinds of movement and feeling while enabling others, and that this suppression is not neutral — remains as relevant in the era of GPS navigation and algorithmic route optimisation as it was in 1950s Paris."},
        ],
        x:300,y:420,color:"#38bdf8",status:"consolidated",source:"manual",
      },
      {
        id: "pilgrimage", term: "Pilgrimage",
        definition: "Movement that is purposive but genuinely transformative: the pilgrim moves toward a destination but is changed by the journey in ways that the destination alone could not produce. Pilgrimage is one of the oldest and most widely distributed human practices of structured movement — present in virtually every religious and cultural tradition — and it operates at the intersection of wayfaring (you accumulate knowledge and self through the movement itself), moving freely (the choice to undertake a pilgrimage is a profound act of self-direction), and community (pilgrimages are typically undertaken with others, forming temporary communities of shared movement and shared purpose).",
        thinkers: ["Turner","Chaucer","Thoreau","Snyder","Coleman"],
        tags: ["movement","place","community","practice","transformation"],
        connections: [
          {to:"wayfaring",label:"purposive form of"},
          {to:"moving-freely",label:"deep form of"},
          {to:"seasonal-rhythm",label:"often structured by"},
          {to:"re-inhabitation",label:"extended pilgrimage as"},
          {to:"membership",label:"pilgrimage produces temporary"},
        ],
        nuances: [
          {thinker:"Turner",note:"Victor Turner's analysis of pilgrimage as a liminal phenomenon — drawing on his concept of liminality from The Ritual Process — shows how the journey places the pilgrim between social structures, outside their normal roles and identities, in a state of communitas (the direct, unmediated fellowship of fellow travelers). The transformation pilgrimage produces is not merely spiritual but social: you return as someone who has been outside the ordinary world and come back."},
          {thinker:"Contemporary forms",note:"Pilgrimage is undergoing a contemporary revival — the Camino de Santiago, the Kumano Kodō in Japan, the revival of the Glastonbury Tor walk — that suggests it meets a need that secular movement culture does not. People undertake these journeys not necessarily for religious reasons but for the specific quality of movement they offer: purposive, communal, slow, transformative. They are a counter to lockstep."},
          {thinker:"Cross-network",note:"Pilgrimage connects to Seasonal Rhythm in the Methodologies vocabulary — many pilgrimage routes are seasonally structured — and to Membership in the Livelihoods vocabulary: the temporary community of the pilgrimage is one of the few contemporary forms of genuine membership that modernity still reliably produces."},
        ],
        x:700,y:420,color:"#a78bfa",status:"consolidated",source:"manual",
      },
      {
        id: "nomadology", term: "Nomadology",
        definition: "Deleuze and Guattari's concept, from A Thousand Plateaus: an alternative to the history and philosophy of the State, which is always sedentary — always concerned with fixing, capturing, and organising movement. Nomadology studies the nomad, who is not the opposite of the settler (the nomad does not roam randomly) but a different relationship to territory: the nomad holds territory by moving through it, following the seasonal paths of water and grass, inhabiting the smooth space that the State's striated space is always trying to capture and organise. Nomadology is not a romanticisation of actual nomadic peoples but a conceptual tool for thinking about forms of movement and existence that resist capture.",
        thinkers: ["Deleuze","Guattari"],
        tags: ["movement","Deleuze","ontology","space","politics"],
        connections: [
          {to:"flows-of-desire",label:"nomad follows"},
          {to:"wayfaring",label:"nomad as wayfarer"},
          {to:"lockstep",label:"what nomadology resists"},
          {to:"lines-of-movement",label:"nomad moves on smooth space"},
          {to:"deterritorialization",label:"nomad practices"},
        ],
        nuances: [
          {thinker:"Deleuze & Guattari",note:"The distinction between smooth and striated space is central to nomadology: smooth space is open, undifferentiated, navigated by landmarks and winds and stars — it is lived rather than mapped. Striated space is measured, divided, organised by the State — it is mapped rather than lived. The nomad inhabits smooth space; the citizen inhabits striated space. The history of modernity is the progressive striation of smooth space."},
          {thinker:"Caution",note:"Deleuze and Guattari are careful to note that nomadology is a conceptual tool, not a lifestyle recommendation. They are not suggesting that everyone should become a nomad, or romanticising the actual historical and contemporary situation of nomadic peoples, who are under constant pressure from sedentary states. The nomad is a figure for thinking about movement and resistance, not a model for imitation."},
        ],
        x:700,y:540,color:"#34d399",status:"consolidated",source:"manual",
      },
      {
        id: "embodied-movement", term: "Embodied Movement",
        definition: "Movement understood as a primary mode of knowing and being rather than as mere displacement in space. The moving body does not travel through a pre-given world but constitutes its world through movement: proprioception, kinaesthesia, the felt sense of momentum and resistance — these are not secondary to cognition but its ground. Merleau-Ponty's phenomenology of the body establishes that perception is fundamentally motoric: we see the world as a field of possible movements, not as a visual display. The dancer, the craftsperson, the walker all know their worlds through a bodily intelligence that precedes and exceeds conceptual thought.",
        thinkers: ["Merleau-Ponty","Sheets-Johnstone","Ingold","Laban"],
        tags: ["movement","embodiment","phenomenology","cognition","practice"],
        connections: [
          {to:"wayfaring",label:"bodily basis of"},
          {to:"moving-freely",label:"felt quality of"},
          {to:"flows-of-desire",label:"desire felt in body"},
          {to:"slow-knowledge",label:"bodily knowing as"},
          {to:"attention",label:"bodily attention"},
        ],
        nuances: [
          {thinker:"Merleau-Ponty",note:"In Phenomenology of Perception, Merleau-Ponty argues that the body is not an object in the world but the subject of perception — the vehicle by which we have a world at all. The body schema — the pre-reflective sense of where one's body is and what it can do — is the ground of all spatial experience. To move is not to relocate an object (the body) in space but to enact space from within."},
          {thinker:"Sheets-Johnstone",note:"Maxine Sheets-Johnstone's The Primacy of Movement argues that movement is the foundational phenomenon of animate life — we are not beings who happen to move but movement that happens to take the form of beings. Her phenomenological analyses of dance, animal locomotion, and infant development show how movement is always already meaningful, always already intentional, always already a form of knowing."},
          {thinker:"Laban",note:"Rudolf Laban's movement analysis — developed in the context of dance and later applied in theatre, therapy, and organisational life — provides a vocabulary for the qualities of movement: effort, space, shape, flow. Laban's framework is one of the few systematic attempts to describe the phenomenology of movement from within, as it is felt rather than as it appears from outside."},
        ],
        x:160,y:160,color:"#818cf8",status:"consolidated",source:"manual",
      },
    ],
  };
