// Non-Places & Simulation vocabulary
// Auto-extracted from semantic-network.jsx

export const simulationNetwork = {
    id: "simulation", label: "Non-Places & Simulation",
    subtitle: "Augé, Baudrillard — Hyperreality, Space & the Precession of Signs",
    accent: "#f87171", storageKey: "semantic-network-simulation",
    initialNodes: [
      {
        id: "non-place", term: "Non-Place",
        definition: "Marc Augé's term for spaces that cannot be defined as relational, historical, or concerned with identity — spaces of transit, consumption, and circulation. Airports, motorways, supermarkets, hotel chains, and refugee camps are his canonical examples. A non-place cannot be inhabited in the full sense; it can only be passed through, read, or consumed. It produces a specific kind of subject: anonymous, contractual, stripped of social identity and reduced to a role defined by the transaction at hand.",
        thinkers: ["Augé","de Certeau","Mauss"],
        tags: ["space","modernity","identity","transit","phenomenology"],
        connections: [
          {to:"supermodernity",label:"symptom of"},
          {to:"similitude",label:"produces"},
          {to:"contractual-identity",label:"generates"},
          {to:"text-as-mediator",label:"experienced through"},
          {to:"nowhere-everywhereness",label:"sensation of"},
          {to:"simulacrum",label:"Baudrillard's parallel"},
          {to:"junkspace",label:"architectural version"},
        ],
        nuances: [
          {thinker:"Augé",note:"Augé is careful to note that non-place and place are not absolute categories — they are polarities, and any actual space contains elements of both. The same airport terminal may be a place of deep personal significance for one traveler and pure non-place for another passing through."},
          {thinker:"De Certeau",note:"Augé draws on de Certeau's distinction between space and place — for de Certeau, space is practiced place, animated by movement and use. Non-places invert this: they are spaces that actively resist being turned into places through practice or memory."},
        ],
        x:350,y:300,color:"#f87171",status:"consolidated",source:"manual",
      },
      {
        id: "supermodernity", term: "Supermodernity",
        definition: "Augé's alternative to postmodernity as a diagnosis of the contemporary condition — characterised not by the end of modernity but by its excess. Three excesses define it: excess of time (too much history, too many events to process into meaning), excess of space (the physical world shrunk by transport and communication to the point of ubiquitous access), and excess of ego (radical individualism and self-referentiality as the default orientation). Non-places are the spatial symptom of supermodernity — they are what you build when these three excesses combine in brick and glass.",
        thinkers: ["Augé"],
        tags: ["modernity","space","time","identity","critique"],
        connections: [
          {to:"non-place",label:"produces"},
          {to:"similitude",label:"generates"},
          {to:"hyperreality",label:"Baudrillard's parallel diagnosis"},
          {to:"nowhere-everywhereness",label:"spatial experience of"},
        ],
        nuances: [
          {thinker:"Augé",note:"Supermodernity is deliberately not postmodernity — Augé resists the claim that we have left modernity behind. Rather, the modern project of rationalisation, mobility, and individualism has simply intensified beyond the point where its contradictions can be managed. More of the same, pushed past a threshold."},
          {thinker:"Excess of ego",note:"The excess of ego dimension is perhaps the most underexplored: supermodernity produces subjects who are individually over-referenced — saturated with images and information about themselves and their choices — while being socially under-connected. The selfie in the airport terminal is its perfect emblem."},
        ],
        x:180,y:180,color:"#fb923c",status:"consolidated",source:"manual",
      },
      {
        id: "contractual-identity", term: "Contractual Identity",
        definition: "Augé's term for what the non-place offers in place of social identity: you are addressed only as a role, identified by a ticket, a passport, or a credit card. The non-place does not know you; it processes you. Contractual identity is temporary, legible, and thin — the minimum information required to permit a transaction. It is the opposite of the thick, accumulated identity produced by place, membership, and long-term community. In the non-place, you exist only insofar as you can prove your right to be there.",
        thinkers: ["Augé"],
        tags: ["identity","space","modernity","phenomenology","critique"],
        connections: [
          {to:"non-place",label:"produced by"},
          {to:"similitude",label:"correlate of"},
          {to:"nowhere-everywhereness",label:"experienced as"},
          {to:"sign-value",label:"sign-system of"},
        ],
        nuances: [
          {thinker:"Augé",note:"Contractual identity is paradoxically both liberating and alienating. Augé notes that the non-place offers a kind of temporary freedom from social obligation — you are anonymous, unrecognised, released from the weight of who you are at home. But this freedom is hollow: it is the freedom of the passenger, not the freedom of the citizen."},
          {thinker:"Cross-network",note:"Contractual identity is the thin self that uprootedness produces in Weil's terms, and what Arendt would call the reduction of the person to the animal laborans — a being defined only by its participation in biological and economic process, stripped of the dimensions of work and action."},
        ],
        x:180,y:420,color:"#f472b6",status:"consolidated",source:"manual",
      },
      {
        id: "similitude", term: "Similitude",
        definition: "Augé's term for the spatial homogeneity produced by non-places: everywhere feels the same. The airport in Dubai and the airport in Dublin share the same controlled lighting, the same smooth surfaces, the same signage logic, the same brand environments. Similitude is not merely aesthetic repetition but the active erasure of the particular — the suppression of everything that makes a place irreducibly different from every other place. It is produced by the replication of models across space, and is thus the spatial expression of Baudrillard's precession.",
        thinkers: ["Augé"],
        tags: ["space","modernity","identity","phenomenology","homogeneity"],
        connections: [
          {to:"non-place",label:"produced by"},
          {to:"supermodernity",label:"spatial expression of"},
          {to:"nowhere-everywhereness",label:"generates feeling of"},
          {to:"junkspace",label:"architectural form of"},
          {to:"precession",label:"spatial consequence of"},
        ],
        nuances: [
          {thinker:"Augé",note:"Similitude is different from simple standardisation. What produces it is not just that buildings look the same but that they operate according to the same logic — the same relationship between user and space, the same mediating role of text and image, the same suppression of local particularity in favour of the legible and transactable."},
        ],
        x:350,y:160,color:"#facc15",status:"consolidated",source:"manual",
      },
      {
        id: "text-as-mediator", term: "Text as Mediator",
        definition: "Augé's observation that in non-places, the individual's relationship to space is mediated through instructions and injunctions — signs, screens, announcements, directions — rather than through direct, embodied, social experience. You do not inhabit an airport; you read it. This makes the non-place fundamentally linguistic in character: it communicates rather than resonates. The traveler moves through a continuous stream of imperatives — check in here, remove shoes, proceed to gate — that constitute the space as a text to be decoded rather than a place to be lived.",
        thinkers: ["Augé"],
        tags: ["space","language","phenomenology","modernity","identity"],
        connections: [
          {to:"non-place",label:"experienced through"},
          {to:"advertising-as-tautology",label:"advertising as form of"},
          {to:"obscenity",label:"saturation of the visible"},
          {to:"ecstasy-of-communication",label:"produces"},
        ],
        nuances: [
          {thinker:"Augé",note:"The text of the non-place addresses a generic, abstract subject — not you, but 'the passenger', 'the customer', 'the user'. This is the linguistic correlate of contractual identity: just as the space knows you only as a role, the text speaks to you only as a function."},
          {thinker:"Baudrillard connection",note:"Where Augé sees mediation through text as a feature of non-places specifically, Baudrillard generalises this into a theory of the sign-system as such: all of consumer culture operates through the mediation of signs that refer not to things but to other signs."},
        ],
        x:520,y:160,color:"#38bdf8",status:"consolidated",source:"manual",
      },
      {
        id: "nowhere-everywhereness", term: "Nowhere-Everywhereness",
        definition: "Augé's evocative phrase for the specific spatial sensation produced by non-places: you are nowhere in particular and could be anywhere at all, simultaneously. The airport advertisement does not address you as someone who is here, in this city, with this history — it addresses a generic consumer-subject who could be anywhere on earth. Nowhere-everywhereness is both a spatial condition and a subjective one: the non-place produces a self that is equally unlocated, equally interchangeable, equally without the coordinates of particular belonging.",
        thinkers: ["Augé"],
        tags: ["space","phenomenology","identity","modernity","sensation"],
        connections: [
          {to:"non-place",label:"sensation of"},
          {to:"similitude",label:"generated by"},
          {to:"contractual-identity",label:"correlate of"},
          {to:"supermodernity",label:"experience of"},
          {to:"hyperreality",label:"Baudrillard's version"},
        ],
        nuances: [
          {thinker:"Augé",note:"Nowhere-everywhereness has an odd phenomenological texture — it is not disorienting in the way of being lost, because the non-place is saturated with orientation cues. You always know which gate to go to. The disorientation is of a different order: not spatial but existential. You know where the gate is; you do not know where you are."},
        ],
        x:520,y:420,color:"#c084fc",status:"consolidated",source:"manual",
      },
      {
        id: "simulacrum", term: "Simulacrum / Simulacra",
        definition: "Baudrillard's core term: a copy without an original, an image that refers to no prior reality. The simulacrum is not a bad representation of something real — it is something that has substituted itself for the real entirely, erasing the memory of what it replaced. Non-places are spatial simulacra: they have the form of a location — address, architecture, function — without the substance of a place. Disneyland is a simulacrum not because it is fake but because it is more coherent, more legible, more consistent than the reality it supposedly imitates.",
        thinkers: ["Baudrillard","Plato (origin of term)"],
        tags: ["simulation","image","modernity","space","Baudrillard"],
        connections: [
          {to:"non-place",label:"spatial form of"},
          {to:"four-phases",label:"fourth phase of image"},
          {to:"hyperreality",label:"produces condition of"},
          {to:"precession",label:"what precession produces"},
          {to:"sign-value",label:"circulates as"},
          {to:"junkspace",label:"built form of"},
        ],
        nuances: [
          {thinker:"Baudrillard",note:"Baudrillard inherits the term from Plato but inverts its valuation. For Plato, the simulacrum is an inferior copy of a copy — twice removed from the real. For Baudrillard, there is no original to be removed from. The simulacrum doesn't degrade reality; it replaces it so completely that the question of an original no longer makes sense."},
          {thinker:"Disneyland",note:"Disneyland is Baudrillard's most famous example: it exists not as a fantasy escape from a real America but as a machine to make the surrounding, 'real' America seem real by contrast. Disneyland is presented as imaginary so that we can believe the rest is real — when in fact the rest is equally simulated."},
        ],
        x:660,y:300,color:"#f87171",status:"consolidated",source:"manual",
      },
      {
        id: "four-phases", term: "Four Phases of the Image",
        definition: "Baudrillard's historical schema for the progressive detachment of the sign from reality, each phase marking a deeper severance. Phase one: the image reflects a basic reality — representation as faithful mirror. Phase two: it masks and distorts that reality — ideology and propaganda. Phase three: it masks the absence of any basic reality — the political speech that performs substance without containing it. Phase four: the image bears no relation to reality whatsoever — it is pure simulacrum, self-referential, generating its own closed loop of meaning. Each phase does not simply follow the previous but absorbs and neutralises it.",
        thinkers: ["Baudrillard"],
        tags: ["simulation","image","history","Baudrillard","epistemology"],
        connections: [
          {to:"simulacrum",label:"fourth phase produces"},
          {to:"precession",label:"logic of fourth phase"},
          {to:"hyperreality",label:"condition of fourth phase"},
          {to:"self-fulfilling-model",label:"operational form of"},
          {to:"advertising-as-tautology",label:"advertising as fourth phase"},
        ],
        nuances: [
          {thinker:"Baudrillard",note:"The four phases are not a linear historical sequence that all cultures pass through in order — they are conditions that can coexist. A political system can operate simultaneously at phase two (deliberate propaganda) and phase four (pure spectacle without referent). What matters is which logic is dominant."},
          {thinker:"Phase three as most dangerous",note:"Phase three is arguably the most insidious: where phase two can in principle be exposed as distortion (there is still a reality being distorted), phase three masks the absence of anything to expose. You cannot unmask a lie if there is no truth being concealed — only a void being papered over."},
        ],
        x:820,y:160,color:"#818cf8",status:"consolidated",source:"manual",
      },
      {
        id: "precession", term: "Precession of Simulacra",
        definition: "Baudrillard's most fundamental and vertiginous claim: in hyperreality, the model comes before the real it was supposed to represent. The map precedes and generates the territory rather than the other way around. Signs no longer refer to a world that exists independently of them; they produce a world in their own image. This is not merely representation or ideology — it is a structural inversion of the relationship between sign and referent. Precession names the direction of causality in a simulation culture: from model to real, not from real to model.",
        thinkers: ["Baudrillard","Borges (Map fable)"],
        tags: ["simulation","Baudrillard","epistemology","modernity","image"],
        connections: [
          {to:"simulacrum",label:"what precession produces"},
          {to:"four-phases",label:"logic of fourth phase"},
          {to:"hyperreality",label:"condition of"},
          {to:"self-fulfilling-model",label:"operational form"},
          {to:"similitude",label:"spatial consequence"},
        ],
        nuances: [
          {thinker:"Baudrillard",note:"Baudrillard opens Simulacra and Simulation with a riff on a Borges fable about a map so detailed it covers the territory entirely — and inverts it. Today, he argues, it is the territory that is the map: the real has become a pale reflection of the model that was supposed to represent it."},
          {thinker:"Cross-network",note:"Precession is structurally related to assimilation in the TD/Rupture network: both describe the dominance of a prior framework over incoming reality. The difference is that Piaget's assimilation is a cognitive mechanism operating at the level of the individual, while Baudrillard's precession is a civilisational condition — the collective cognitive framework of an entire culture."},
        ],
        x:820,y:300,color:"#c084fc",status:"consolidated",source:"manual",
      },
      {
        id: "self-fulfilling-model", term: "Self-Fulfilling Model",
        definition: "The operational form that precession takes in everyday cultural, political, and economic life: models do not merely predict or represent their objects — they actively produce them. A political campaign already contains within itself a complete image of what it should look and sound like, and reality is then shaped to conform to that image. A market forecast shapes the market movement it claims to describe. A polling model influences the votes it purports to measure. The model is the event — not its cause or its effect but its substance.",
        thinkers: ["Baudrillard"],
        tags: ["simulation","Baudrillard","modernity","politics","epistemology"],
        connections: [
          {to:"precession",label:"operational form of"},
          {to:"four-phases",label:"fourth phase in action"},
          {to:"hyperreality",label:"mechanism of"},
          {to:"advertising-as-tautology",label:"advertising as"},
          {to:"implosion",label:"result of"},
        ],
        nuances: [
          {thinker:"Baudrillard",note:"The self-fulfilling model is where Baudrillard's theory becomes most directly applicable to contemporary politics and media. His argument is not just that campaigns are managed or staged — it is that there is no authentic political substance being managed. The management is the substance. The image is not a skin over a body; it is the whole organism."},
          {thinker:"Predictive processing",note:"Baudrillard's self-fulfilling model has a structural resonance with predictive processing in cognitive science — the idea that the brain generates a prior model of reality and filters perception through it. But where predictive processing describes a useful adaptive mechanism, Baudrillard describes its pathological cultural form: a collective prior so dominant that it no longer updates on incoming reality."},
        ],
        x:820,y:420,color:"#f59e0b",status:"consolidated",source:"manual",
      },
      {
        id: "hyperreality", term: "Hyperreality",
        definition: "The condition produced when simulacra and models precede and generate the real to the point where the distinction between real and simulation collapses — and where the simulation is in some ways more vivid, more coherent, and more total than any real it might have once corresponded to. Hyperreality is not a false reality concealing a true one. There is no true one behind it. It is more real than real: more intensely present, more internally consistent, more saturated with meaning — while being precisely evacuated of the depth that genuine reality would have.",
        thinkers: ["Baudrillard"],
        tags: ["simulation","Baudrillard","modernity","space","phenomenology"],
        connections: [
          {to:"simulacrum",label:"produced by"},
          {to:"precession",label:"condition of"},
          {to:"four-phases",label:"state of fourth phase"},
          {to:"obscenity",label:"phenomenological texture of"},
          {to:"ecstasy-of-communication",label:"subjective experience of"},
          {to:"non-place",label:"spatial form of"},
          {to:"junkspace",label:"built environment of"},
        ],
        nuances: [
          {thinker:"Baudrillard",note:"Baudrillard's attitude toward hyperreality is deliberately ambiguous — he does not simply condemn it. In America, he is visibly seduced by the hyperreal landscape of the desert and Las Vegas, finding in it an almost sublime fascination. This is what separates him from Augé, who retains a humanist mourning for the lost place."},
          {thinker:"Disneyland revisited",note:"In hyperreality, Disneyland is not the exception but the paradigm. The logic of the theme park — controlled atmosphere, total legibility, managed experience, the erasure of ambiguity — is the logic of the supermarket, the airport, the political campaign, and eventually the social media feed."},
        ],
        x:660,y:160,color:"#f87171",status:"consolidated",source:"manual",
      },
      {
        id: "obscenity", term: "Obscenity",
        definition: "Baudrillard's term — used in a specific, non-moral sense — for the condition of total visibility: things being too present, too lit-up, with no shadow, depth, mystery, or remainder. In hyperreality, obscenity is not what is hidden or transgressive but what is maximally exposed. The supermarket, the airport, the television screen all share this quality: a merciless, even, artificial illumination that flattens everything onto the same plane of visibility. Nothing is left in the dark; nothing retains interiority. The obscene is the over-visible.",
        thinkers: ["Baudrillard"],
        tags: ["simulation","Baudrillard","phenomenology","space","sensation"],
        connections: [
          {to:"hyperreality",label:"phenomenological texture of"},
          {to:"ecstasy-of-communication",label:"produces"},
          {to:"text-as-mediator",label:"saturation of"},
          {to:"advertising-as-tautology",label:"advertising as"},
          {to:"non-place",label:"sensorial quality of"},
        ],
        nuances: [
          {thinker:"Baudrillard",note:"Obscenity in this sense is the opposite of the erotic, the secret, the ambiguous. It is the condition of the pornographic — not in the sexual sense but in the sense of something shown with total explicitness, without remainder. Consumer spaces are obscene in precisely this way: their lighting, their signage, their surfaces leave nothing to imagination or interpretation."},
          {thinker:"Sensorial dimension",note:"This is where Baudrillard comes closest to a phenomenology of non-places: the fluorescent lighting of the supermarket, the identical brightness of the airport terminal at 3am and 3pm — these are not incidental but constitutive of the hyperreal space. The light is the message."},
        ],
        x:660,y:440,color:"#f472b6",status:"consolidated",source:"manual",
      },
      {
        id: "ecstasy-of-communication", term: "Ecstasy of Communication",
        definition: "Baudrillard's description, from his 1987 essay of the same name, of what happens to the subject under the total proliferation of information and images: not enlightenment or enrichment but a glazed, saturated, anaesthetised stupefaction. The subject is overwhelmed by signals that carry no real meaning — rendered ecstatic in the original sense, beside themselves, outside themselves, unable to locate an interior position from which to respond. It is the inner experience of walking through an airport terminal past screens, brand logos, departure boards, and advertising — overstimulated and emptied simultaneously.",
        thinkers: ["Baudrillard"],
        tags: ["simulation","Baudrillard","phenomenology","sensation","communication"],
        connections: [
          {to:"obscenity",label:"produced by"},
          {to:"hyperreality",label:"subjective experience of"},
          {to:"implosion",label:"result of"},
          {to:"text-as-mediator",label:"overload of"},
          {to:"advertising-as-tautology",label:"produced by"},
        ],
        nuances: [
          {thinker:"Baudrillard",note:"Ecstasy here carries its etymological force — ek-stasis, standing outside oneself. The subject of hyperreality is beside themselves not through rapture but through saturation: the self has been colonised by the screen, the sign, the image, to the point where there is no interior left from which to experience them."},
          {thinker:"Stupefaction",note:"Baudrillard describes the condition as producing a kind of stupefaction — a glazed, passive, receiving state that resembles the condition of watching television for hours: information continues to arrive, but meaning has long since stopped accumulating. This is the phenomenology of the non-place at its most acute."},
        ],
        x:500,y:540,color:"#34d399",status:"consolidated",source:"manual",
      },
      {
        id: "implosion", term: "Implosion",
        definition: "Where industrial modernity operated by explosion — expansion, production, energy outward, the growth of the social, the multiplication of distinctions — hyperreality operates by implosion: the collapse of distinctions, the folding of meaning back on itself, the compression of the social into media and simulation. The political implodes into spectacle; the real implodes into the model; the subject implodes into the screen; the social implodes into the mass. Implosion is Baudrillard's name for the direction of travel of late modernity — not toward revolution or catastrophe but toward a kind of airless, self-referential density.",
        thinkers: ["Baudrillard"],
        tags: ["simulation","Baudrillard","modernity","critique","process"],
        connections: [
          {to:"hyperreality",label:"mechanism of"},
          {to:"ecstasy-of-communication",label:"produces"},
          {to:"self-fulfilling-model",label:"result of"},
          {to:"simulacrum",label:"what simulacra produce collectively"},
        ],
        nuances: [
          {thinker:"Baudrillard",note:"Implosion is the opposite of the Marxist expectation of explosion — revolution as the outward rupture of a system under its own contradictions. Baudrillard argues that consumer society defuses its contradictions not by resolving them but by absorbing them into the simulation. Critique itself implodes into the system — becomes a sign among signs, a lifestyle choice, a brand."},
          {thinker:"The masses",note:"In In the Shadow of the Silent Majorities, Baudrillard extends implosion to describe the masses: not an agent of history but a black hole that absorbs all meaning directed at it without reflecting it back. Political campaigns, media messages, and ideological appeals all disappear into the mass without producing the responses they were designed to elicit."},
        ],
        x:820,y:540,color:"#818cf8",status:"consolidated",source:"manual",
      },
      {
        id: "sign-value", term: "Sign-Value",
        definition: "Baudrillard's extension of the Marxist value-theory: beyond use-value (what an object does) and exchange-value (what it costs), consumer objects have sign-value — what they signify in the social code of status, identity, distinction, and belonging. In consumer culture, sign-value has become the dominant logic: objects are consumed not for their utility or their price but for their position in a self-referential system of signs. A designer bag is not purchased for its capacity to carry things but for what it says — and what it says is determined by its position relative to other signs, not by any quality intrinsic to the object.",
        thinkers: ["Baudrillard","Marx (origin)","Saussure (sign theory)"],
        tags: ["simulation","Baudrillard","economics","identity","consumption"],
        connections: [
          {to:"simulacrum",label:"circulates as"},
          {to:"advertising-as-tautology",label:"what advertising circulates"},
          {to:"contractual-identity",label:"identity constituted through"},
          {to:"four-phases",label:"logic of consumer culture"},
        ],
        nuances: [
          {thinker:"Baudrillard",note:"In The System of Objects and Consumer Society, Baudrillard argues that the sign-system of consumer culture operates like a language: objects only mean in relation to other objects. There is no fixed referent — the meaning of luxury, of youth, of rebellion, of authenticity is perpetually redefined by the system in its own interest."},
          {thinker:"Saussure connection",note:"Baudrillard draws on Saussure's structural linguistics: signs derive meaning from their differences from other signs, not from any positive content. Consumer goods operate by the same logic — a brand is defined by what it is not, and its meaning shifts as the system of differences shifts."},
        ],
        x:500,y:160,color:"#fb923c",status:"consolidated",source:"manual",
      },
      {
        id: "advertising-as-tautology", term: "Advertising as Tautology",
        definition: "Baudrillard's observation that advertising in hyperreality does not communicate information about products — it simply asserts their existence and circulates their sign-value in a closed loop. The smiling person, the warm light, the aspirational backdrop do not refer outward to a world; they fold back on themselves. The ad is the product, in a functional sense — it produces the desire that motivates the purchase more directly than any quality of the thing itself. Advertising is therefore not persuasion but repetition: the tautological insistence of the sign on its own existence.",
        thinkers: ["Baudrillard"],
        tags: ["simulation","Baudrillard","consumption","communication","image"],
        connections: [
          {to:"sign-value",label:"circulates"},
          {to:"four-phases",label:"fourth phase of image"},
          {to:"text-as-mediator",label:"dominant form of"},
          {to:"obscenity",label:"produces"},
          {to:"similitude",label:"produces spatial"},
        ],
        nuances: [
          {thinker:"Baudrillard",note:"The key insight is that advertising has become self-referential: it no longer refers to a product or even to a lifestyle but to itself — to the fact of advertising, to the ambient flow of images that constitutes the consumer environment. This is why advertising that is obviously absurd or self-consciously artificial still works: sincerity and irony are both absorbed into the tautology."},
        ],
        x:350,y:440,color:"#facc15",status:"consolidated",source:"manual",
      },
      {
        id: "junkspace", term: "Junkspace",
        definition: "Rem Koolhaas's architectural parallel to Baudrillard's hyperreality: the generic, climate-controlled, brand-saturated built environment produced by late capitalism — shopping malls, airports, office parks, hotel lobbies, theme parks, and the connecting tissue between them. Junkspace is what happens when architecture is produced from a model or brand template rather than grown from the particularity of a place, program, or culture. It is the built form of the simulacrum: physically present and technically functional, but without the depth, specificity, or resistance that constitutes architecture in the traditional sense.",
        thinkers: ["Koolhaas"],
        tags: ["space","architecture","modernity","critique","phenomenology"],
        connections: [
          {to:"non-place",label:"architectural version of"},
          {to:"simulacrum",label:"built form of"},
          {to:"similitude",label:"material expression of"},
          {to:"hyperreality",label:"built environment of"},
          {to:"obscenity",label:"sensorial quality of"},
        ],
        nuances: [
          {thinker:"Koolhaas",note:"Koolhaas's essay Junkspace (2001) is written in a deliberately breathless, list-like style that mimics the quality of the space it describes — accumulative, undifferentiated, without hierarchy or pause. The form enacts the argument. He is simultaneously diagnosing and, with characteristic ambivalence, half-celebrating: junkspace is the authentic architecture of our moment, even if it is terrible."},
          {thinker:"Benjamin connection",note:"Junkspace is in many ways the updated version of Walter Benjamin's Arcades — the glass-and-iron shopping passages of nineteenth-century Paris that Benjamin read as the dreamworld of commodity capitalism. The arcade was the prototype; the airport terminal and the mall are its fully realised successors."},
        ],
        x:180,y:540,color:"#38bdf8",status:"consolidated",source:"manual",
      },
    ],
  };
