// Viennese Aesthetic Vocabulary vocabulary
// Auto-extracted from semantic-network.jsx

export const viennaNetwork = {
    id: "vienna", label: "Viennese Aesthetic Vocabulary",
    subtitle: "1860–1910 — Art, Craft & Urban Form",
    accent: "#f59e0b", storageKey: "semantic-network-vienna",
    initialNodes: [
      { id:"gesamtkunstwerk", term:"Gesamtkunstwerk",
        definition:"The integration of all artistic disciplines — architecture, interior, furniture, graphics, objects — into a unified aesthetic whole. Originating in Wagnerian aesthetics, in Vienna the term became a social philosophy: the fragmentation of style was seen to reflect the fragmentation of modern life itself. A unified aesthetic environment was thus both an artistic and a moral ambition.",
        thinkers:["Wagner","Hoffmann","Moser","Klimt"], tags:["design","unity","modernity","social"],
        connections:[{to:"stil",label:"requires"},{to:"lebensform",label:"shapes"},{to:"kunstgewerbe",label:"elevates"},{to:"ornament",label:"contested by Loos"},{to:"wiener-werkstaette",label:"institutionalised in"},{to:"sitte-stadtbild",label:"urban parallel"}],
        nuances:[{thinker:"Secession",note:"For the Secessionists, Gesamtkunstwerk meant dissolving the hierarchy between fine art and applied art — no object too small to deserve artistic care."},{thinker:"Wiener Werkstätte",note:"Hoffmann and Moser pursued a total aesthetic environment, designing everything from buildings to cutlery, but the movement's expense risked turning reform into elite luxury."},{thinker:"Loos",note:"Loos violently rejected the Gesamtkunstwerk ethos, arguing in Ornament and Crime that decorative integration was cultural regression rather than progress."}],
        x:350,y:420,color:"#f59e0b",status:"consolidated",source:"manual" },
      { id:"kunstgewerbe", term:"Kunstgewerbe",
        definition:"Applied or decorative art — the broad field of craft-based objects made with aesthetic intention: furniture, ceramics, textiles, metalwork, bookbinding. In Vienna from the 1860s, Kunstgewerbe became a reform project: if industrial production was inevitable, then elevating the taste embedded in everyday objects could civilize capitalism and shape the moral condition of a society.",
        thinkers:["Eitelberger","Hoffmann","Moser"], tags:["craft","reform","industry","education"],
        connections:[{to:"materialgerechtigkeit",label:"governed by"},{to:"stilbildung",label:"requires"},{to:"formgefuehl",label:"cultivates"},{to:"gesamtkunstwerk",label:"absorbed into"},{to:"mak",label:"institutionalised at"}],
        nuances:[{thinker:"Eitelberger / MAK",note:"The Museum für Kunst und Industrie framed Kunstgewerbe as a liberal bourgeois civilizing project: train craftsmen in taste, and industrial society can be redeemed."},{thinker:"Wiener Werkstätte",note:"Hoffmann and Moser radicalised the concept — not reform of mass production but the creation of hand-made objects of complete artistic integrity."}],
        x:800,y:500,color:"#fb923c",status:"consolidated",source:"manual" },
      { id:"stil", term:"Stil",
        definition:"Style as a total principle — not mere surface decoration but the coherent formal language that unifies all expressions of a historical moment or a designed environment. For Vienna's reformers, the absence of a genuine modern Stil was the symptom of cultural crisis. Finding or inventing one adequate to modern life was the central task of art, architecture, and design.",
        thinkers:["Semper","Riegl","Hoffmann","Klimt"], tags:["form","history","modernity","coherence"],
        connections:[{to:"gesamtkunstwerk",label:"unified by"},{to:"stilbildung",label:"cultivated through"},{to:"kunstwollen",label:"driven by"},{to:"ornament",label:"expressed in"}],
        nuances:[{thinker:"Semper",note:"Gottfried Semper argued each historical epoch produces its own integral style from material, technique, and social function — a style cannot be arbitrarily chosen."},{thinker:"Riegl",note:"Riegl's Stilfragen traced the autonomous formal evolution of ornamental style, resisting reductive material or functional explanations."}],
        x:500,y:130,color:"#facc15",status:"consolidated",source:"manual" },
      { id:"kunstwollen", term:"Kunstwollen",
        definition:"Literally 'art-will' or 'artistic volition' — Alois Riegl's concept for the inner purposive drive that shapes the formal character of art in a given time and place. Kunstwollen resists reduction: it is neither material determinism nor imitation of nature, but an autonomous creative impulse that produces specific formal solutions. Every age has its own Kunstwollen, which gives its art integrity even when judged 'primitive' by other standards.",
        thinkers:["Riegl"], tags:["theory","form","will","history"],
        connections:[{to:"stil",label:"produces"},{to:"ornament",label:"manifests in"},{to:"materialgerechtigkeit",label:"in tension with"},{to:"stilbildung",label:"historically expresses"}],
        nuances:[{thinker:"Riegl",note:"Introduced in Stilfragen (1893) and developed in Spätrömische Kunstindustrie (1901). Kunstwollen opposes Semper's materialist theory — form is not determined by technique or function but by an inner artistic will."}],
        x:500,y:280,color:"#4ade80",status:"consolidated",source:"manual" },
      { id:"materialgerechtigkeit", term:"Materialgerechtigkeit",
        definition:"Material honesty or material fidelity — the principle that the formal treatment of an object should be truthful to the nature of its material. Wood should look and behave like wood; stone like stone; metal like metal. Violation of this principle was treated as both aesthetic failure and moral dishonesty. It became a cornerstone of Vienna's applied arts reform.",
        thinkers:["Semper","Eitelberger","Hoffmann"], tags:["craft","ethics","form","material"],
        connections:[{to:"kunstgewerbe",label:"grounds"},{to:"formgefuehl",label:"trained alongside"},{to:"ornament",label:"constrains"},{to:"stil",label:"contributes to"}],
        nuances:[{thinker:"Semper",note:"Semper's material theory of style saw each craft technique — weaving, ceramics, carpentry — as generating specific formal possibilities. Honesty to material was structural, not merely ethical."}],
        x:670,y:560,color:"#34d399",status:"consolidated",source:"manual" },
      { id:"stilbildung", term:"Stilbildung",
        definition:"Style-formation or taste-cultivation — the educational and social process through which sensitivity to coherent formal language is developed in craftsmen, designers, and the public. For museum reformers, Stilbildung was the practical goal: through drawing classes, museum collections, and workshops, the capacities for aesthetic judgment could be trained into a population.",
        thinkers:["Eitelberger","MAK reformers"], tags:["education","reform","taste","craft"],
        connections:[{to:"kunstgewerbe",label:"aims to elevate"},{to:"formgefuehl",label:"develops"},{to:"mak",label:"pursued at"},{to:"stil",label:"towards"}],
        nuances:[{thinker:"MAK reformers",note:"The founding logic of the Österreichisches Museum für Kunst und Industrie: display exemplary historical craft objects so that students and craftsmen absorb formal principles by looking."}],
        x:650,y:420,color:"#38bdf8",status:"consolidated",source:"manual" },
      { id:"formgefuehl", term:"Formgefühl",
        definition:"Feeling for form — an aesthetic sensibility or intuition that allows a craftsman or designer to judge the rightness of formal decisions. Not reducible to rules, Formgefühl is a cultivated capacity, something between instinct and trained judgment. The concept marks the limits of rationalist design theory: ultimately form-giving requires a felt, embodied sense that cannot be fully codified.",
        thinkers:["Semper","Riegl","Eitelberger"], tags:["sensibility","craft","embodiment","judgment"],
        connections:[{to:"materialgerechtigkeit",label:"applied through"},{to:"stilbildung",label:"cultivated by"},{to:"kunstgewerbe",label:"essential to"},{to:"lebensform",label:"embedded in"}],
        nuances:[{thinker:"Semper",note:"In Der Stil, Semper treats Formgefühl as the tacit dimension of craft knowledge — the accumulated wisdom of making that exceeds verbal instruction."}],
        x:300,y:200,color:"#818cf8",status:"consolidated",source:"manual" },
      { id:"ornament", term:"Ornament",
        definition:"Decorative form applied to or integrated into objects, surfaces, and buildings. In Vienna, ornament was the central contested terrain: for Riegl, ornament expressed autonomous formal will; for Semper, it was grounded in material technique; for the Secessionists, it was the vehicle of aesthetic unity; for Loos, it was crime — the mark of cultural degeneracy and wasted labour.",
        thinkers:["Riegl","Semper","Klimt","Loos","Hoffmann"], tags:["form","decoration","controversy","modernity"],
        connections:[{to:"kunstwollen",label:"expresses"},{to:"gesamtkunstwerk",label:"unifies in"},{to:"materialgerechtigkeit",label:"constrained by"},{to:"loos-kritik",label:"condemned in"},{to:"stil",label:"vehicle of"}],
        nuances:[{thinker:"Riegl",note:"Stilfragen (1893) traces a continuous formal evolution of ornament across cultures, arguing its logic is autonomous — not derived from nature or technique but from inner formal will."},{thinker:"Loos",note:"Ornament and Crime (1908): ornament is cultural regression. The modern person has overcome the need to decorate surfaces."},{thinker:"Secession",note:"For Klimt and the Secessionists, ornament was not regressive but the very medium through which psychological depth and aesthetic unity could be achieved."}],
        x:700,y:200,color:"#f472b6",status:"consolidated",source:"manual" },
      { id:"lebensform", term:"Lebensform",
        definition:"Form of life — the idea that aesthetic choices are not separable from the way a person or community lives. A coherent Lebensform means that artistic sensibility permeates daily existence: the home, clothing, social rituals, urban environment. For Vienna's art reformers, the goal was not merely beautiful objects but a beautiful and unified mode of life.",
        thinkers:["Hoffmann","Secession","Wiener Werkstätte"], tags:["life","unity","social","ethics"],
        connections:[{to:"gesamtkunstwerk",label:"realised through"},{to:"formgefuehl",label:"rooted in"},{to:"wiener-werkstaette",label:"pursued by"},{to:"sitte-stadtbild",label:"extended into city"}],
        nuances:[{thinker:"Wiener Werkstätte",note:"Hoffmann and Moser designed the complete environment — from building to spoon — because coherent Lebensform required no aesthetic gap between architecture and daily utensil."}],
        x:100,y:470,color:"#c084fc",status:"consolidated",source:"manual" },
      { id:"wiener-werkstaette", term:"Wiener Werkstätte",
        definition:"The Vienna Workshops — founded 1903 by Josef Hoffmann and Koloman Moser. The Werkstätte attempted to realise a complete aesthetic environment: furniture, textiles, metalwork, ceramics, clothing, books. It embodied the ideal of craft integrity and artistic unity, but its objects were expensive and its clientele wealthy — a persistent tension between social reform ambitions and elite luxury production.",
        thinkers:["Hoffmann","Moser"], tags:["institution","craft","design","reform"],
        connections:[{to:"gesamtkunstwerk",label:"institutionalises"},{to:"kunstgewerbe",label:"radicalises"},{to:"lebensform",label:"pursues"},{to:"secession",label:"emerges from"}],
        nuances:[{thinker:"Hoffmann",note:"The Werkstätte programme: 'We want to establish intimate contact between public, designer, and craftsman.' But the price of hand-craft made this public largely the Viennese upper bourgeoisie."}],
        x:180,y:500,color:"#fb923c",status:"consolidated",source:"manual" },
      { id:"secession", term:"Secession",
        definition:"The Vienna Secession — founded 1897, when Klimt, Hoffmann, Moser and others broke from the conservative Künstlerhaus. Its motto 'Der Zeit ihre Kunst, der Kunst ihre Freiheit' expressed its double ambition: a new style adequate to modernity, and freedom from academic hierarchy. It explicitly dissolved the boundary between fine and applied art.",
        thinkers:["Klimt","Hoffmann","Moser","Olbrich"], tags:["institution","avant-garde","modernity","reform"],
        connections:[{to:"gesamtkunstwerk",label:"pursues"},{to:"stil",label:"seeks new"},{to:"wiener-werkstaette",label:"generates"},{to:"loos-kritik",label:"criticised by"}],
        nuances:[{thinker:"Klimt",note:"Klimt's Beethoven Frieze (1902) was the movement's most complete Gesamtkunstwerk experiment — painting, architecture, music, and sculpture unified for a single exhibition."}],
        x:160,y:360,color:"#4ade80",status:"consolidated",source:"manual" },
      { id:"mak", term:"MAK / Museum für Kunst und Industrie",
        definition:"The Österreichisches Museum für Kunst und Industrie (today the MAK), founded 1864 by Rudolf von Eitelberger — the first applied arts museum in the German-speaking world, modelled on the V&A in London. Its founding logic: display historical craft masterworks so that designers and craftsmen absorb their formal principles through direct encounter.",
        thinkers:["Eitelberger"], tags:["institution","education","reform","history"],
        connections:[{to:"kunstgewerbe",label:"promotes"},{to:"stilbildung",label:"enables"},{to:"materialgerechtigkeit",label:"teaches"}],
        nuances:[{thinker:"Eitelberger",note:"Eitelberger was a liberal bourgeois art historian who believed the state had a duty to cultivate taste — the museum as pedagogical instrument for the modernization of craft."}],
        x:900,y:390,color:"#38bdf8",status:"consolidated",source:"manual" },
      { id:"sitte-stadtbild", term:"Stadtbild / Sitte",
        definition:"Camillo Sitte's conception of the city as an artistically composed visual whole — analysed in Städtebau nach seinen künstlerischen Grundsätzen (1889). Sitte treated the historic city as a painter treats a composition: spatial enclosure, visual sequence, the irregular placement of monuments within plazas. Though he never uses 'Gesamtkunstwerk', he treats the city as a unified artistic organism grown through time.",
        thinkers:["Sitte"], tags:["urbanism","space","history","composition"],
        connections:[{to:"gesamtkunstwerk",label:"urban parallel to"},{to:"lebensform",label:"spatial dimension of"},{to:"stil",label:"historically embedded"},{to:"ringstrasse",label:"critique of"}],
        nuances:[{thinker:"Sitte",note:"Sitte's model is emergent and historical; the Secessionists' is consciously designed and programmatic. Both treat the built environment as aesthetic totality, but by opposite methods."}],
        x:780,y:570,color:"#facc15",status:"consolidated",source:"manual" },
      { id:"loos-kritik", term:"Loos / Ornament and Crime",
        definition:"Adolf Loos's radical counter-position to the Viennese aesthetic reform consensus — crystallised in his 1908 essay Ornament und Verbrechen. Loos argued that ornament is not cultural richness but cultural lag: the impulse to decorate belongs to primitive and criminal psychology. Modern culture means restraint, the separation of art from everyday utility, and the embrace of plain, functional surfaces.",
        thinkers:["Loos"], tags:["critique","modernity","rupture","design"],
        connections:[{to:"ornament",label:"condemns"},{to:"gesamtkunstwerk",label:"rejects"},{to:"secession",label:"breaks from"},{to:"materialgerechtigkeit",label:"shares concern with"}],
        nuances:[{thinker:"Loos",note:"Paradoxically, Loos shared the reform movement's concern for material honesty, but drew the opposite conclusion: strip ornament away entirely rather than refining it."}],
        x:500,y:560,color:"#f472b6",status:"consolidated",source:"manual" },
      { id:"ringstrasse", term:"Ringstraße",
        definition:"Vienna's monumental boulevard constructed from the 1860s onward — a planned urban ensemble of historicist public buildings intended to represent imperial civic identity. For Vienna's reform generation, the Ringstraße became the symbol of everything wrong: historical eclecticism, stylistic pastiche, surface spectacle without genuine cultural unity.",
        thinkers:["Sitte (critic)","Loos (critic)","Secession (reaction)"], tags:["urbanism","history","eclecticism","critique"],
        connections:[{to:"sitte-stadtbild",label:"critiqued by"},{to:"stil",label:"lacks genuine"},{to:"loos-kritik",label:"symptom addressed by"},{to:"secession",label:"provokes"}],
        nuances:[{thinker:"Schorske",note:"Carl Schorske's Fin-de-Siècle Vienna reads the Ringstraße as the liberal bourgeoisie's self-representation in stone — and the aesthetic revolt of the 1890s as a generational rejection of that image."}],
        x:940,y:210,color:"#818cf8",status:"consolidated",source:"manual" },
      { id:"kunstgenuss", term:"Kunstgenuss",
        definition:"Art-enjoyment or art-pleasure — the felt, bodily experience of aesthetic absorption in a work. In the Vienna reform context the term carried ethical weight — if the objects and environments of daily life were well made, Kunstgenuss would become democratically available, not confined to the museum.",
        thinkers:["Eitelberger","Riegl","Secession"], tags:["aesthetics","pleasure","experience","sensibility"],
        connections:[{to:"kunstwollen",label:"felt response to"},{to:"formgefuehl",label:"related to"},{to:"lebensform",label:"enriches"},{to:"zweckfreiheit",label:"enabled by"}],
        nuances:[{thinker:"Riegl",note:"Riegl's formal analysis of art is ultimately in service of recovering Kunstgenuss — the goal of art history is to make us feel again what earlier cultures felt when they produced their forms."}],
        x:750,y:310,color:"#f472b6",status:"consolidated",source:"manual" },
      { id:"kunsterlebnis", term:"Kunsterlebnis",
        definition:"Art-experience — a more phenomenologically weighted term than Kunstgenuss, emphasising the lived, temporal encounter with a work rather than the pleasure it yields. Kunsterlebnis implies that genuine engagement with art transforms the one who undergoes it: it is an event, not merely a sensation.",
        thinkers:["Dilthey","Gadamer","Secession"], tags:["aesthetics","experience","phenomenology","transformation"],
        connections:[{to:"kunstgenuss",label:"deepens into"},{to:"lebensform",label:"shapes"},{to:"gesamtkunstwerk",label:"produced by"},{to:"zweckfreiheit",label:"requires"}],
        nuances:[{thinker:"Gadamer",note:"Gadamer inherits the term and radicalises it: the Kunsterlebnis is not a private psychological event but a claim the work makes on us — an encounter that reorganises our understanding."}],
        x:800,y:160,color:"#818cf8",status:"consolidated",source:"manual" },
      { id:"zweckfreiheit", term:"Zweckfreiheit",
        definition:"Freedom from purpose — the Kantian idea that genuine aesthetic experience involves a suspension of instrumental thinking, a contemplation of form for its own sake rather than for any end it serves.",
        thinkers:["Kant","Schiller","Secession","Hoffmann"], tags:["aesthetics","freedom","autonomy","making"],
        connections:[{to:"kunstgenuss",label:"enables"},{to:"kunsterlebnis",label:"condition of"},{to:"secession",label:"declared by"},{to:"gesamtkunstwerk",label:"animates"}],
        nuances:[{thinker:"Kant",note:"Kant's Critique of Judgment: the beautiful pleases without concept and without interest — Zweckfreiheit (purposiveness without purpose) is the formal structure of this disinterested pleasure."}],
        x:250,y:130,color:"#facc15",status:"consolidated",source:"manual" },
      { id:"grossstadt", term:"Grossstadt",
        definition:"The metropolis — the great city as a qualitatively new form of human experience. Around 1900 in German-speaking culture, Grossstadt named both an empirical fact and a contested aesthetic question: whether the modern city could become a unified artistic whole. Otto Wagner's position — that the Grossstadt demands and makes possible a new artistic vision at the level of the entire urban plan — is the foreground of this node.",
        thinkers:["Otto Wagner","Sitte","Simmel","Toennies","Loos"], tags:["urbanism","modernity","planning","vision"],
        connections:[{to:"ringstrasse",label:"supersedes"},{to:"sitte-stadtbild",label:"diverges from"},{to:"gesamtkunstwerk",label:"scales up to city"},{to:"lebensform",label:"shapes at urban scale"}],
        nuances:[{thinker:"Otto Wagner",note:"In Moderne Architektur (1895), Wagner argues that only an artist — not an engineer or bureaucrat — can give the expanding metropolis its necessary form."},{thinker:"Simmel",note:"Georg Simmel's Die Grossstadt und das Geistesleben (1903): the metropolis produces the blasé type — a person who has deadened their responses to survive overstimulation."}],
        x:940,y:470,color:"#38bdf8",status:"consolidated",source:"manual" },
      { id:"beethoven-frieze", term:"Beethoven Frieze (Klimt, 1902)",
        definition:"Gustav Klimt's monumental wall painting created for the 14th Secession exhibition, 1902 — designed as a temporary work, intended to be destroyed after the exhibition closed. The Frieze is the most concentrated single artifact in which the Vienna network's tensions become visible: Gesamtkunstwerk within Gesamtkunstwerk, ornament as psychological language, the dissolution of fine and decorative art.",
        thinkers:["Klimt","Beethoven (source)","Schiller (via Beethoven)","Wagner (Gesamtkunstwerk concept)"], tags:["artifact","ornament","narrative","aesthetics","process"],
        connections:[{to:"gesamtkunstwerk",label:"exemplifies within"},{to:"secession",label:"centrepiece of 1902 exhibition"},{to:"ornament",label:"deploys as psychological language"},{to:"kunsterlebnis",label:"designed to produce"}],
        nuances:[{thinker:"Process / Temporality",note:"The Frieze was designed to be temporary — Gesamtkunstwerk as event rather than object. Its accidental survival changes its meaning."}],
        x:360,y:560,color:"#f59e0b",status:"consolidated",source:"manual" },
      { id:"gemischter-satz", term:"Gemischter Satz",
        definition:"The indigenous Viennese field-blend wine — grown on the hills within the city boundary, pressed from many grape varieties harvested together. As a cultural form, Gemischter Satz embodies a social philosophy antithetical to the Gesamtkunstwerk's controlled aesthetic totality: its beauty is unplanned, emergent from mixture rather than unified vision.",
        thinkers:["Viennese folk culture","Schorske (social context)"], tags:["culture","social","wine","city"],
        connections:[{to:"kaffeehausleben",label:"counterpart to"},{to:"lebensform",label:"popular form of"},{to:"gesamtkunstwerk",label:"informal counterpoint to"}],
        nuances:[{thinker:"Unplanned totality",note:"Gemischter Satz achieves unity without a guiding artistic will. The blend emerges from cohabitation over time, not design."}],
        x:180,y:200,color:"#4ade80",status:"consolidated",source:"manual" },
      { id:"schmaeh", term:"Schmaeh",
        definition:"An untranslatable Viennese mode of social interaction — not quite irony, not quite charm, not quite cynicism, but a way of holding warmth and detachment simultaneously. Schmaeh says serious things through apparent lightness; it deflects sentimentality without becoming cold.",
        thinkers:["Karl Kraus","Nestroy","Freud (jokes)","Thomas Bernhard"], tags:["culture","language","irony","social"],
        connections:[{to:"kaffeehausleben",label:"performed in"},{to:"wiener-gemutlichkeit",label:"unsettles"},{to:"loos-kritik",label:"shares mode with"},{to:"dekadenz",label:"coping response to"}],
        nuances:[{thinker:"Karl Kraus",note:"Kraus's satirical method in Die Fackel is Schmaeh elevated to literary form — the deadpan quotation of an opponent's words as the most devastating critique."}],
        x:120,y:260,color:"#facc15",status:"consolidated",source:"manual" },
      { id:"kaffeehausleben", term:"Kaffeehausleben",
        definition:"Coffeehouse life — the social institution through which Viennese intellectual, artistic, and political culture actually reproduced itself. The Viennese Kaffeehaus was simultaneously an office, salon, postal address, reading room, and debating chamber.",
        thinkers:["Karl Kraus","Altenberg","Trotsky","Herzl","Klimt"], tags:["culture","institution","social","language"],
        connections:[{to:"gemischter-satz",label:"counterpart to"},{to:"schmaeh",label:"primary venue of"},{to:"secession",label:"social substrate of"},{to:"lebensform",label:"defines Viennese"}],
        nuances:[{thinker:"Social function",note:"The Kaffeehaus solved a specific Viennese problem: apartments were small and cold, but the coffeehouse was warm, spacious, and cheap."}],
        x:100,y:370,color:"#fb923c",status:"consolidated",source:"manual" },
      { id:"wiener-gemutlichkeit", term:"Wiener Gemutlichkeit",
        definition:"Viennese cosiness or conviviality — the quality of social warmth, unhurried ease, and pleasurable togetherness. But it has a profound underside: Gemutlichkeit as cultural anaesthetic, as the specifically Viennese talent for making the unbearable comfortable, for conducting the business of decline in a pleasant tone of voice.",
        thinkers:["Karl Kraus","Bernhard","Canetti","Zweig"], tags:["culture","social","atmosphere","critique"],
        connections:[{to:"schmaeh",label:"expressed through"},{to:"kaffeehausleben",label:"cultivated in"},{to:"dekadenz",label:"masks"},{to:"lebensform",label:"popular version of"}],
        nuances:[{thinker:"Karl Kraus",note:"Kraus saw Gemutlichkeit as Vienna's most dangerous quality: it was the cultural solvent that dissolved all serious distinctions."}],
        x:120,y:160,color:"#34d399",status:"consolidated",source:"manual" },
      { id:"ringstrasse-gesellschaft", term:"Ringstrasse-Gesellschaft",
        definition:"Ringstraße society — the specific social formation that built the boulevard, commissioned its institutions, and constituted the dominant cultural public of late nineteenth-century Vienna: the liberal upper bourgeoisie, largely but not exclusively Jewish.",
        thinkers:["Schorske","Zweig","Freud","Mahler","Schnitzler"], tags:["social","class","history","institution"],
        connections:[{to:"ringstrasse",label:"built and inhabited"},{to:"secession",label:"patronised and was challenged by"},{to:"wiener-gemutlichkeit",label:"performed"},{to:"dekadenz",label:"symptom of exhaustion of"}],
        nuances:[{thinker:"Schorske",note:"Schorske's Fin-de-Siecle Vienna argues that the Ringstrasse-Gesellschaft's turn to aestheticism was a response to political failure."}],
        x:870,y:130,color:"#818cf8",status:"consolidated",source:"manual" },
      { id:"dekadenz", term:"Dekadenz / Fin-de-siecle Stimmung",
        definition:"Decadence and the mood of the fin de siecle — the pervasive sense in Vienna around 1890-1910 of civilisational lateness, of living at an ending, of hypercultivation as simultaneously the highest achievement and the surest sign of exhaustion.",
        thinkers:["Hofmannsthal","Schnitzler","Klimt","Nietzsche","Schorske"], tags:["culture","history","atmosphere","crisis","modernity"],
        connections:[{to:"ringstrasse-gesellschaft",label:"experienced by"},{to:"wiener-gemutlichkeit",label:"concealed by"},{to:"secession",label:"aesthetic response to"},{to:"gesamtkunstwerk",label:"intensified pursuit of"}],
        nuances:[{thinker:"Hofmannsthal",note:"Hugo von Hofmannsthal's Ein Brief (1902) is the canonical text of Viennese Dekadenz: a fictional letter describing complete loss of faith in language."}],
        x:780,y:130,color:"#f87171",status:"consolidated",source:"manual" },
    ],
  };
