// Worlding & Re-Worlding vocabulary
// Auto-extracted from semantic-network.jsx

export const worldingNetwork = {
    id: "worlding", label: "Worlding & Re-Worlding",
    subtitle: "Heidegger, Haraway, Escobar — Making, Dwelling & Pluriversal Worlds",
    accent: "#a78bfa", storageKey: "semantic-network-worlding",
    initialNodes: [
      {
        id: "worlding", term: "Worlding",
        definition: "The active, ongoing process by which worlds are made, sustained, and transformed — not a single creative act but a continuous practice of bringing a world into being and keeping it going. Worlding insists that worlds are not given but made: through practice, attention, relationship, language, and material engagement. The term deliberately nominalises a verb — 'world' as something you do, not something you inhabit passively. It sits at the intersection of Heidegger's ontological analysis of being-in-the-world, Haraway's feminist and multispecies extensions, and the enactivist tradition's account of cognition as world-enactment.",
        thinkers: ["Heidegger","Haraway","Escobar","Ingold","Varela"],
        tags: ["worlding","ontology","practice","becoming","cosmology"],
        connections: [
          {to:"cosmopoiesis",label:"cosmic scale of"},
          {to:"being-in-the-world",label:"grounded in"},
          {to:"bringing-forth",label:"enacted through"},
          {to:"worldliness",label:"felt as"},
          {to:"within-withal",label:"structure of"},
          {to:"pluriversality",label:"implies plurality of"},
          {to:"re-worlding",label:"transformative form of"},
          {to:"worldly-desire",label:"motivated by"},
        ],
        nuances: [
          {thinker:"Heidegger",note:"For Heidegger, 'world' is not an objective container of entities but the horizon of meaning within which things show up as what they are. Worlding names the event by which this horizon opens — not a human achievement but something that happens to and through Dasein as it exists."},
          {thinker:"Haraway",note:"Haraway extends worlding beyond the human: in her late work, worlding is what all critters do — bacteria, fungi, humans, and their symbiotic assemblages all participate in making worlds together. Her phrase 'making kin' is a form of worlding — an invitation to build new relational configurations across difference."},
          {thinker:"Ingold",note:"Tim Ingold's concept of dwelling and his contrast between 'building' and 'dwelling' maps closely onto worlding as an ongoing, relational, attentive practice rather than a constructive act."},
        ],
        x:500,y:300,color:"#a78bfa",status:"consolidated",source:"manual",
      },
      {
        id: "cosmopoiesis", term: "Cosmopoiesis",
        definition: "The world creating itself — the autopoietic, self-organising process by which the cosmos generates, sustains, and transforms itself through its own internal dynamics. Cosmopoiesis names the largest possible scale of worlding: not human world-making or even multispecies world-making, but the generative creativity of the cosmos as such. It resists both the mechanistic image of the universe as a machine running according to external laws and the theological image of creation as the act of an external designer. The cosmos is its own maker; its creativity is immanent, not imposed.",
        thinkers: ["Whitehead","Stengers","Latour","Escobar"],
        tags: ["worlding","cosmology","ontology","process","creativity"],
        connections: [
          {to:"worlding",label:"cosmic scale of"},
          {to:"bringing-forth",label:"cosmic form of"},
          {to:"pluriversality",label:"source of plural worlds"},
          {to:"worldly-desire",label:"what desires express"},
          {to:"autopoiesis",label:"cosmic extension of"},
        ],
        nuances: [
          {thinker:"Whitehead",note:"Alfred North Whitehead's process philosophy is the deepest philosophical source of cosmopoiesis: reality as a process of creative advance, each actual occasion contributing something genuinely new to the universe. Creativity is the ultimate category — not a property of minds but the character of the cosmos as such."},
          {thinker:"Stengers",note:"Isabelle Stengers's cosmopolitics draws on cosmopoiesis: her 'cosmos' is not the universe of physics but the undetermined, risky whole of all that is — a cosmos that is always more than what any single practice or world-version can capture."},
          {thinker:"Escobar",note:"Arturo Escobar's pluriversal politics is grounded in cosmopoiesis: if the cosmos is genuinely creative and plural, then the existence of many worlds is not a problem to be resolved by one true account but the expression of the cosmos's own generative nature."},
        ],
        x:300,y:150,color:"#c084fc",status:"consolidated",source:"manual",
      },
      {
        id: "being-in-the-world", term: "Being-in-the-World",
        definition: "Heidegger's foundational concept from Being and Time: the insistence that Dasein (human existence) is always already in a world — not a subject that then reaches out to an external object-world, but a being whose very constitution is worldly. Being-in is not spatial containment but existential involvement: to be is to be engaged, caring, oriented. The world is not what surrounds us but what we are always already in the midst of — the horizonal structure of significance within which things, people, and possibilities show up as what they are.",
        thinkers: ["Heidegger"],
        tags: ["worlding","ontology","Heidegger","phenomenology","existence"],
        connections: [
          {to:"worlding",label:"grounds"},
          {to:"worldliness",label:"produces sense of"},
          {to:"within-withal",label:"within dimension of"},
          {to:"dwelling",label:"fullest expression of"},
          {to:"bringing-forth",label:"how world is maintained"},
        ],
        nuances: [
          {thinker:"Heidegger",note:"Being-in-the-world is hyphenated deliberately — it is a single unified structure, not three separate things joined together. The hyphens resist the Cartesian picture of an inner subject confronting an outer world. For Heidegger, that picture is a derivative abstraction from a more primordial involvement that is never not already in place."},
          {thinker:"Against Descartes",note:"Being-in-the-world is Heidegger's most fundamental argument against Cartesian dualism: the problem of how a subject gets in touch with an external world is a pseudo-problem, generated by the false abstraction of a self-enclosed subject. We never start inside; we start in the midst."},
        ],
        x:300,y:420,color:"#818cf8",status:"consolidated",source:"manual",
      },
      {
        id: "dwelling", term: "Dwelling",
        definition: "For Heidegger, in the essay Building Dwelling Thinking (1951), dwelling is the fundamental character of being-in-the-world — not a mode of accommodation but the way mortals are on the earth. To dwell is to spare, to preserve, to let things be what they are. Building is possible only on the basis of dwelling — we do not first build and then dwell, but building emerges from and serves the more primordial orientation of dwelling. Ingold extends this: dwelling is knowing a place through the body, through seasonal rhythms, through the accumulated practice of inhabitation rather than the imposition of a design.",
        thinkers: ["Heidegger","Ingold","Casey"],
        tags: ["worlding","Heidegger","place","practice","phenomenology"],
        connections: [
          {to:"being-in-the-world",label:"fullest expression of"},
          {to:"worldliness",label:"cultivated through"},
          {to:"bringing-forth",label:"the making that dwelling requires"},
          {to:"within-withal",label:"how worlds are inhabited"},
        ],
        nuances: [
          {thinker:"Heidegger",note:"The German bauen (building) shares a root with buan (to dwell) and bin (I am) — Heidegger traces this etymology to argue that being and dwelling are inseparable. To be human is to dwell; to dwell is to build; but building that is not grounded in dwelling produces the homelessness of modernity."},
          {thinker:"Ingold",note:"Ingold's dwelling perspective contrasts with the 'building perspective' of Western modernity: where the latter imposes a pre-formed design onto passive matter, the former attends to the grain of materials, the patterns of weather, the habits of animals — and lets form emerge from that attentive engagement."},
          {thinker:"Cross-network",note:"Dwelling connects directly to Re-Inhabitation in the Livelihoods network and to Slow Knowledge — all three name the kind of knowing and being that accumulates through sustained, embodied engagement with a particular place over time."},
        ],
        x:160,y:300,color:"#34d399",status:"consolidated",source:"manual",
      },
      {
        id: "bringing-forth", term: "Bringing Forth the World",
        definition: "From the enactivist tradition of Maturana, Varela, and Thompson: the central claim that cognition is not the representation of a pre-given world by an inner mental process, but the enactment or bringing-forth of a world through the organism's structure-determined interactions with its environment. The world that a living being inhabits is not found but made — brought forth through the activity of living itself. This is the biological and cognitive parallel to Heidegger's ontological worlding: worlds are not discovered but enacted, and different forms of life enact different worlds.",
        thinkers: ["Maturana","Varela","Thompson"],
        tags: ["worlding","enactivism","cognition","biology","ontology"],
        connections: [
          {to:"worlding",label:"enactivist account of"},
          {to:"being-in-the-world",label:"cognitive parallel to"},
          {to:"cosmopoiesis",label:"biological form of"},
          {to:"pluriversality",label:"grounds plurality of worlds"},
          {to:"autopoiesis",label:"grounded in"},
        ],
        nuances: [
          {thinker:"Varela, Thompson & Rosch",note:"In The Embodied Mind (1991), Varela, Thompson, and Rosch argue that cognition is not the recovery of a pre-given world but the mutual specification of organism and environment through ongoing sensorimotor coupling. The world is a domain of significance brought forth by living activity."},
          {thinker:"Maturana",note:"Humberto Maturana's formulation is the most radical: there is no objective world independent of the observer — not because the world is a mental construct, but because the world an organism can perceive and act within is always the world relative to its structural organisation. Different organisations bring forth different worlds."},
          {thinker:"Cross-network",note:"Bringing-forth connects to Pickering's Performative Idiom in the TD/Rupture network: both refuse the representational picture of cognition as inner mirror of outer world, and insist instead that knowing is a form of doing — an active engagement that constitutes rather than merely reflects its objects."},
        ],
        x:700,y:420,color:"#4ade80",status:"consolidated",source:"manual",
      },
      {
        id: "autopoiesis", term: "Autopoiesis",
        definition: "Maturana and Varela's term for the self-producing, self-maintaining organisation characteristic of living systems: a network of processes that produces the components that constitute the network. An autopoietic system produces itself — it is both the producer and the product of its own organisation. Autopoiesis is the biological foundation of bringing-forth: it is because living systems are autopoietic that they enact worlds rather than simply respond to them.",
        thinkers: ["Maturana","Varela"],
        tags: ["worlding","biology","enactivism","ontology","process"],
        connections: [
          {to:"bringing-forth",label:"biological basis of"},
          {to:"cosmopoiesis",label:"cosmic extension of"},
          {to:"worlding",label:"living form of"},
          {to:"haraway-sympoiesis",label:"extended to sympoiesis"},
        ],
        nuances: [
          {thinker:"Maturana & Varela",note:"Autopoiesis was introduced in Autopoiesis and Cognition (1980) to distinguish living from non-living systems: what makes something alive is not its material composition but its organisational form — the circular, self-referential network of production that maintains the system as a distinguishable whole in an environment."},
          {thinker:"Luhmann extension",note:"Luhmann extended autopoiesis to social systems — communications producing communications in a self-referential network. This extension is controversial but fruitful: it suggests that social worlds too are autopoietic in a functional sense, bringing themselves forth through their own internal dynamics."},
        ],
        x:700,y:540,color:"#38bdf8",status:"consolidated",source:"manual",
      },
      {
        id: "worldly-desire", term: "Worldly Desire",
        definition: "The desire to be part of a world — not desire directed at an object within the world, but the more primordial orientation toward belonging to a world as such. Worldly desire is the affective dimension of worlding: what draws a being toward participation, membership, and entanglement. It is the desire to matter within a web of relationships that extends beyond the self, to be claimed by a world rather than merely to inhabit it. Worldly desire is prior to any particular desire for any particular thing — it is the condition of possibility of caring about anything at all.",
        thinkers: ["Haraway","Weil (resonance)","Whitehead (resonance)"],
        tags: ["worlding","desire","ontology","belonging","ethics"],
        connections: [
          {to:"worlding",label:"motivates"},
          {to:"worldliness",label:"expressed as"},
          {to:"cosmopoiesis",label:"cosmic creativity felt from inside"},
          {to:"re-worlding",label:"drives"},
          {to:"within-withal",label:"orients toward"},
        ],
        nuances: [
          {thinker:"Haraway",note:"Haraway's insistence on 'staying with the trouble' — refusing both optimism and despair in favour of committed, relational engagement with the damaged world — is an expression of worldly desire: a desire to be in and of the world, even in its broken condition."},
          {thinker:"Weil resonance",note:"Worldly desire resonates with Weil's concept of attention: both name an orientation of the whole self toward something beyond the self, without agenda. The difference is that worldly desire is explicitly affective and participatory — it wants to be part of the world, not merely to perceive it clearly."},
          {thinker:"Whitehead resonance",note:"In Whitehead's process philosophy, every actual occasion involves a 'subjective aim' — an orientation toward contribution to the ongoing creative advance of the universe. Worldly desire is what this cosmic orientation feels like from the inside of a living, caring being."},
        ],
        x:500,y:160,color:"#f472b6",status:"consolidated",source:"manual",
      },
      {
        id: "worldliness", term: "Worldliness",
        definition: "The sense or quality of being genuinely part of a world — the felt texture of belonging to a web of relationships, significances, and practices that extends beyond the self and constitutes a coherent domain of existence. Worldliness is not sophistication in the everyday sense but an ontological condition: the degree to which a being is genuinely embedded in, formed by, and responsive to the world it inhabits. To be worldly is to be implicated — to find that the world makes claims on you, shapes you, and requires your participation.",
        thinkers: ["Heidegger","Arendt","Haraway"],
        tags: ["worlding","ontology","belonging","phenomenology","ethics"],
        connections: [
          {to:"worlding",label:"felt quality of"},
          {to:"being-in-the-world",label:"expression of"},
          {to:"dwelling",label:"cultivated through"},
          {to:"worldly-desire",label:"expressed through"},
          {to:"within-withal",label:"what within names"},
        ],
        nuances: [
          {thinker:"Heidegger",note:"For Heidegger, worldliness (Weltlichkeit) is a structural feature of the world as such — the character by which the world is a world rather than a mere aggregate of objects. Things have worldliness insofar as they are caught up in a web of involvements and references that constitutes their being what they are."},
          {thinker:"Arendt",note:"Arendt's sense of worldliness is more explicitly political: the world is what lies between people, what is held in common, what outlasts individual lives. Worldliness is the care for this shared, durable world — its opposite is the world-alienation of modernity."},
          {thinker:"Cross-network",note:"Worldliness is the ontological correlate of Membership in the Livelihoods network: both name the condition of being genuinely of a world or community, shaped by its obligations and constituted by its relationships, rather than merely passing through."},
        ],
        x:300,y:540,color:"#fb923c",status:"consolidated",source:"manual",
      },
      {
        id: "within-withal", term: "Within and Withal",
        definition: "A paired conceptual frame for the double structure of worldly existence. Within names the condition of always already being inside a world — embedded in its practices, shaped by its history, constituted by its relationships. We never encounter the world from outside; we are always within it. Withal names the lateral dimension: being alongside other worlds, other forms of life, other configurations of practice and meaning that are also embedded in the cosmos. Together they describe a cosmology of mutual embeddedness: many worlds, each within the cosmos, each withal the others.",
        thinkers: [],
        tags: ["worlding","ontology","plurality","cosmology","belonging"],
        connections: [
          {to:"worlding",label:"structure of"},
          {to:"being-in-the-world",label:"within dimension"},
          {to:"pluriversality",label:"withal dimension"},
          {to:"worldliness",label:"what within names"},
          {to:"cosmopoiesis",label:"cosmos as the withal of all worlds"},
        ],
        nuances: [
          {thinker:"Within",note:"Within is the phenomenological and ontological claim: there is no view from nowhere, no outside position from which to survey the world as a whole. All knowing, acting, and being is situated inside a world whose horizon we cannot step beyond. This is Heidegger's being-in-the-world and Maturana's structural coupling — existence is always from within."},
          {thinker:"Withal",note:"Withal names what within might obscure: that being within one world does not mean being the only world. To be withal other worlds is to acknowledge their reality, their weight, their claim — to exist alongside them without absorbing them. This is the ethical implication of pluriversality."},
          {thinker:"Cosmos",note:"The cosmos is the name for what all worlds are within and withal simultaneously — not a super-world that contains all worlds as parts, but the condition of their mutual embeddedness, the medium in which worlds coexist without merging or cancelling each other."},
        ],
        x:700,y:160,color:"#facc15",status:"consolidated",source:"manual",
      },
      {
        id: "pluriversality", term: "Pluriversality",
        definition: "The condition and affirmation of genuinely many worlds — not many perspectives on one world (multiculturalism) but many worlds, each with its own ontological specificity. Pluriversality is the political and ontological counterpart to the modern constitution's claim to universality: where Euro-modernism asserts one nature, one rationality, one modernity available to all, pluriversality insists that multiple worlds are real and that no single world has the right to absorb or erase the others. The political project corresponding to pluriversality is the pluriverse: a world in which many worlds fit.",
        thinkers: ["Escobar","Viveiros de Castro","Zapatistas","de la Cadena"],
        tags: ["worlding","ontology","pluriversality","politics","cosmology"],
        connections: [
          {to:"worlding",label:"implies plurality of"},
          {to:"within-withal",label:"withal dimension of"},
          {to:"re-worlding",label:"political project of"},
          {to:"cosmopoiesis",label:"source of plural worlds"},
          {to:"bringing-forth",label:"each world brought forth differently"},
          {to:"islands-of-stability-world",label:"each world as"},
        ],
        nuances: [
          {thinker:"Escobar",note:"Arturo Escobar's Designs for the Pluriverse (2018) argues that design is always an ontological operation: it makes worlds. Pluriversal design would proceed from the premise that multiple ontologies are real and that the task is to create conditions for their coexistence rather than the subsumption of all under one."},
          {thinker:"Zapatistas",note:"The Zapatista slogan 'a world in which many worlds fit' is the political statement of pluriversality in its most direct form — the demand not for inclusion within the existing world-order but for the recognition that other worlds are real and have the right to exist on their own terms."},
          {thinker:"Viveiros de Castro",note:"Amerindian multinaturalism — the assumption of one culture and many natures — is the clearest example of an alternative ontology that pluriversality takes seriously. Indigenous perspectives are not culturally different ways of seeing the same nature; they are ontologically different configurations of what there is."},
          {thinker:"Cross-network",note:"Pluriversality connects directly to the Ontological Turn in the TD/Rupture network: both argue against the Euro-modern claim to be the meta-ontology. The ontological turn is the intellectual movement; pluriversality is its political and ethical expression."},
        ],
        x:700,y:300,color:"#4ade80",status:"consolidated",source:"manual",
      },
      {
        id: "re-worlding", term: "Re-Worlding",
        definition: "The deliberate, transformative practice of making new worlds — or remaking damaged ones — through changed practices, relationships, and material engagements. Re-worlding is worlding under conditions of crisis: when existing worlds have been destroyed, impoverished, or rendered uninhabitable, re-worlding names the creative, political, and ontological work of making liveable worlds again. It is distinguished from mere reform by its ontological ambition: it does not seek to adjust the existing world but to enact different worlds into being.",
        thinkers: ["Haraway","Escobar","Stengers","Tsing"],
        tags: ["worlding","ontology","practice","politics","creativity"],
        connections: [
          {to:"worlding",label:"transformative form of"},
          {to:"pluriversality",label:"political project of"},
          {to:"worldly-desire",label:"driven by"},
          {to:"haraway-sympoiesis",label:"enacted through"},
          {to:"situated-knowledge",label:"requires"},
        ],
        nuances: [
          {thinker:"Haraway",note:"In Staying with the Trouble (2016), Haraway argues for making kin rather than babies — building new relational configurations across species and scales as a response to the Anthropocene. This is re-worlding: not the restoration of a lost world but the making of new symbiotic configurations adequate to the damaged present."},
          {thinker:"Tsing",note:"Anna Tsing's Mushroom at the End of the World traces re-worlding in the ruins of late capitalism: surprising new worlds made in the aftermath of industrial destruction. Re-worlding happens in the cracks, not only in planned alternatives."},
          {thinker:"Cross-network",note:"Re-worlding connects to Re-Rooting and Reterritorialization in the Livelihoods network: all three name the creative, forward-oriented making of new configurations of life on the far side of displacement or destruction. Re-worlding is the ontological register of what re-rooting enacts practically."},
        ],
        x:500,y:450,color:"#f59e0b",status:"consolidated",source:"manual",
      },
      {
        id: "haraway-sympoiesis", term: "Sympoiesis",
        definition: "Haraway's term — borrowed from Beth Dempster — for making-together: in contrast to autopoiesis (self-making), sympoiesis names the collective, boundary-crossing, relational processes by which complex systems make themselves in and through their entanglements with others. Nothing makes itself alone; all making is making-with. Sympoiesis is the relational ontology of worlding: worlds are not made by single actors but by the ongoing, unpredictable entanglements of many kinds of beings across many scales.",
        thinkers: ["Haraway","Dempster","Tsing"],
        tags: ["worlding","ontology","ecology","becoming","relationality"],
        connections: [
          {to:"re-worlding",label:"how re-worlding proceeds"},
          {to:"autopoiesis",label:"relational extension of"},
          {to:"worlding",label:"relational account of"},
          {to:"haraway-tentacular",label:"expressed through"},
          {to:"multispecies-worlds",label:"across species"},
        ],
        nuances: [
          {thinker:"Haraway",note:"In Staying with the Trouble, Haraway contrasts sympoiesis with autopoiesis: where autopoiesis emphasises the bounded self-organisation of living systems, sympoiesis emphasises the unbounded, leaky, entangled character of real living processes. Holobionts — organisms constituted by their microbial communities — are paradigmatic."},
          {thinker:"Making kin",note:"Haraway's slogan 'make kin, not babies' is an invitation to sympoiesis at the social and political scale: instead of reproducing the same relational configurations, make new kinds of kinship across difference — with other species, other generations, other forms of life."},
        ],
        x:840,y:420,color:"#f472b6",status:"consolidated",source:"manual",
      },
      {
        id: "haraway-tentacular", term: "Tentacular Thinking",
        definition: "Haraway's figure for a mode of thought adequate to sympoiesis and re-worlding: thinking that reaches out in multiple directions simultaneously, that forms attachments and entanglements rather than maintaining a clean, bounded, upright perspective. Tentacular thinking is the cognitive correlate of the sympoietic world — it proceeds by following threads of connection rather than surveying from above, by touching and being touched rather than observing from a distance.",
        thinkers: ["Haraway"],
        tags: ["worlding","ontology","epistemology","ecology","methodology"],
        connections: [
          {to:"haraway-sympoiesis",label:"cognitive mode of"},
          {to:"situated-knowledge",label:"epistemological form of"},
          {to:"worlding",label:"mode of"},
          {to:"bringing-forth",label:"how worlds are brought forth tentacularly"},
        ],
        nuances: [
          {thinker:"Haraway",note:"The tentacle figures stand against the upright, forward-gazing, single-perspective figure of the human as master of nature. Octopuses, fungi, mycorrhizal networks — these are Haraway's preferred figures for a different kind of intelligence: distributed, relational, and responsive rather than centralised and commanding."},
          {thinker:"String figures",note:"Haraway uses the game of cat's cradle as a model of tentacular thinking: the figure is never made alone, always requires multiple hands, cannot be sustained without ongoing relationship, and produces something genuinely new with each pass."},
        ],
        x:840,y:280,color:"#c084fc",status:"consolidated",source:"manual",
      },
      {
        id: "situated-knowledge", term: "Situated Knowledge",
        definition: "Haraway's epistemological argument from her 1988 essay: all knowledge is produced from a particular location, body, and perspective — there is no view from nowhere, no god-trick of seeing everything from above while claiming to see from nowhere. Situated knowledge is not relativism: some positions are better for seeing than others, and partial perspectives can be linked together. But the condition of all knowledge is its situatedness — its embeddedness in the bodily, social, and historical conditions of its production.",
        thinkers: ["Haraway"],
        tags: ["worlding","epistemology","ontology","feminism","methodology"],
        connections: [
          {to:"haraway-tentacular",label:"epistemological form of"},
          {to:"re-worlding",label:"requires for"},
          {to:"within-withal",label:"within dimension of knowing"},
          {to:"bringing-forth",label:"knowing as situated bringing-forth"},
        ],
        nuances: [
          {thinker:"Haraway",note:"Situated knowledge is framed against two equally inadequate positions: the relativism that says all views are equally valid, and the objectivism that claims a neutral, nowhere view. Both are evasions of the actual condition of knowing: partial, embodied, implicated, and accountable."},
          {thinker:"Cross-network",note:"Situated knowledge connects to Slow Knowledge in the Livelihoods network — both insist that the most valuable knowledge is the most particular and embodied — and to Pickering's Performative Idiom, which replaces the disembodied observer with an engaged, situated practitioner."},
        ],
        x:700,y:540,color:"#818cf8",status:"consolidated",source:"manual",
      },
      {
        id: "islands-of-stability-world", term: "Worlds as Islands of Stability",
        definition: "Drawing on Pickering's concept from the TD/Rupture network: a world, in the ontological sense relevant to worlding, can be understood as an island of stability — a relatively stabilised configuration of humans, nonhumans, practices, and meanings that holds together as a coherent domain of existence. Worlds are not eternal structures but achievements: sustained through ongoing practice, vulnerable to disruption, and always constituted by the specific assemblage of actors and relationships that make them up. Different islands of stability are different worlds — each tuned into a different configuration of the real.",
        thinkers: ["Pickering","Haraway","Escobar"],
        tags: ["worlding","ontology","STS","stability","practice"],
        connections: [
          {to:"worlding",label:"what a world is"},
          {to:"pluriversality",label:"each world as"},
          {to:"re-worlding",label:"making new islands"},
          {to:"bringing-forth",label:"how islands are brought forth"},
          {to:"within-withal",label:"each island within cosmos withal others"},
        ],
        nuances: [
          {thinker:"Pickering",note:"In Pickering's original usage, islands of stability name the local, achieved configurations of science and shamanism — both stable, both real, both tuned into a lively nature. The extension here treats any coherent form of life — a community, a culture, a species' Umwelt — as an island of stability: an achieved world, not a given one."},
          {thinker:"Vulnerability",note:"The island metaphor carries important implications: islands can be submerged. Worlds are precarious achievements that require ongoing maintenance and can be destroyed — by colonialism, ecological collapse, or cultural erasure. The plurality of worlds is not a permanent given but something that must be actively sustained through pluriversal politics."},
          {thinker:"Cross-network",note:"This node is an explicit bridge to the TD/Rupture network. The bridge allows the concept to carry its full force in both directions: Pickering's epistemological insight enriches the ontological vocabulary of worlding, and the worlding vocabulary deepens the political stakes of Pickering's analysis."},
        ],
        x:160,y:450,color:"#34d399",status:"consolidated",source:"manual",
      },
      {
        id: "multispecies-worlds", term: "Multispecies Worlds",
        definition: "The recognition that worlds are not made only by humans — that every species, and every assemblage of species, brings forth a world in Maturana and Varela's sense, and that these worlds are entangled in ways that make any single-species account radically incomplete. Multispecies worlds thinking draws on Jakob von Uexküll's concept of the Umwelt — the species-specific perceptual and action world of each organism — and extends it through Haraway's sympoiesis and the more-than-human turn in social theory.",
        thinkers: ["Uexküll","Haraway","Tsing","Kohn"],
        tags: ["worlding","ecology","ontology","multispecies","becoming"],
        connections: [
          {to:"worlding",label:"non-human dimension of"},
          {to:"haraway-sympoiesis",label:"made through"},
          {to:"pluriversality",label:"extends to non-human worlds"},
          {to:"bringing-forth",label:"each species brings forth"},
          {to:"cosmopoiesis",label:"the many worlds cosmos brings forth"},
        ],
        nuances: [
          {thinker:"Uexküll",note:"Jakob von Uexküll's Umwelt concept is the biological foundation of multispecies worlds: each organism lives in a perceptual world constituted by its own sensory and motor capacities. The tick's world contains only three signs — warmth, butyric acid, the texture of skin. This is not poverty but specificity: a world perfectly tuned to what matters for that form of life."},
          {thinker:"Tsing",note:"Anna Tsing's work on fungi and forests shows how multispecies worlds are made in practice: the Matsutake mushroom exists only through its entanglement with pine trees, human foragers, global commodity chains, and forest disturbance histories. Its world is a collective achievement of all these actors."},
          {thinker:"Kohn",note:"Eduardo Kohn's How Forests Think argues that the Amazonian forest itself thinks — not metaphorically but in a genuinely semiotic sense. Multispecies worlding extends meaning-making beyond the human, treating signs, selves, and worlds as distributed across the living rather than confined to the linguistic."},
        ],
        x:160,y:160,color:"#fb923c",status:"consolidated",source:"manual",
      },
    ],
  };
